### ISSUE TITLE
Auto build the docker latest image

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia-apps#1]
Whenever a new release is published to `theia-ide/theia` repo, i.e. a tag is created:
- an image `typefox/theia:${tagVersion}`, e.g. `typefox/theia:v0.3.0`, should be build and pushed to Docker Hub
- the latest tag should be aliased to the last published version and pushed to Docker Hub

Probably it can be triggered via npmjs webhooks.

**Comment by kittaakos** [comment]
I do not know if any proxy related things go here or not, but this thread [from Gitter](https://gitter.im/theia-ide/theia?at=5a0d4ce4982ea2653f86b9d4) could be useful.
