### ISSUE TITLE
Use consistent parent image for all theia-apps

### ISSUE THREAD

**Issue by jgbradley1** [theia-ide/theia-apps#100]
Why do the various apps use a different base OS? Is it for testing purposes to try out on different OS's? Or should there be a change for all apps to conform to the same base OS? I see a mix of alpine and ubuntu being used currently.

**Comment by akosyakov** [comment]
What is a need to force everybody to use the same base image?

For different goals, different tools are used, e.g. `theia-full` image is trying to provide support for all extensions, `theia` image is trying to provide the smallest possible image for JS development. What is the issue with that?

**Comment by marcdumais-work** [comment]
Hi @jgbradley1 ,

One reason is that ideally we want to use a lightweight base OS when we can so the resulting image is smaller, but some software we need in some images is not easy to find on some of the lightweight OS, like `Alpine`. Ubuntu is nice in this way, there is lots of pre-built stuff available for it.

**Comment by jgbradley1** [comment]
Thanks for the explanation. After some reflection, I've come to believe it's better to demo Theia on multiple OS's. It shows the broader dev community how versatile Theia can be and and how to deal with it in various environments. I closed the issue just to do some house-cleaning.
