### ISSUE TITLE
Error: "f7" is in collision with something else

### ISSUE THREAD

**Issue by xihaoxiaohao** [theia-ide/theia-apps#108]
````
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 11]
Failed to resolve module: electron
Server worker is ready to accept messages. [ID: 1 | PID: 11]
root INFO Theia app listening on http://0.0.0.0:3000.
Received message which is neither a response nor a notification message:
"3000"
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]
````

_Originally posted by @xihaoxiaohao in https://github.com/theia-ide/theia-apps/issues/92#issuecomment-441928397_

**Comment by marcdumais-work** [comment]
Hi @xihaoxiaohao 

There is an issue registered for this in the main Theia repo, regarding the keybinding collision errors: https://github.com/theia-ide/theia/issues/1888 . 

From the perspective of this repo here, these are errors that can be safely ignored and should not otherwise affect the images. Do you have issues using the image(s), other than seeing the errors above?

**Comment by xihaoxiaohao** [comment]
Thanks @marcdumais-work it's weird, now it's working fine, yesterday the spinner is keep loading...

Also, do you know how can I change the permission of the non-root user so they cannot delete the files inside the /home/theia directory? In the docker file, I tried remove the theia user from the sudo group and setting the permission to 755, but in this way the non-root user theia cannot have access to the node_modules files and the app can't even starting...
