### ISSUE TITLE
yarn theia build timeouts on CI

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia-apps#111]
Hey all, 

Apparently Theia won't compile now on CIs like CircleCI since `theia build` is stuck on a loop somehow.

I used a custom image based on Theia-full with minimal modifications, but it seems even if you give 60m timeouts on CI, the build is stuck on `theia build`, even without `--split-frontend`.

This is tested on [CircleCI Machine Executor (2vCPU, 8GB RAM, 100GB HDD)](https://circleci.com/gh/sr229/theia-openshift/330) configuration.

Tested on interactive as well and it seems to stuck as well on `yarn theia build`.

**Comment by marcdumais-work** [comment]
@sr229 The following commit fixed the CI for the full image and a few other that were intermittently affected: https://github.com/theia-ide/theia-apps/commit/f4245d045e86bf742fbf47336e6e1bd9894f9da7 .

**Comment by marcdumais-work** [comment]
Issue no longer present in this repo; closing
