### ISSUE TITLE
update golang version

### ISSUE THREAD

**Issue by lanrat** [theia-ide/theia-apps#116]
Could we have the go version included in the go and full docker images updated?

The lack of go module support with go >= 1.11 makes it very difficult to work on projects that use go modules, or other go code outside of the gopath.

Thanks.

**Comment by vince-fugnitto** [comment]
I'll close the issue as the `theia-full-docker` image currently has a `go` version of: 


https://github.com/theia-ide/theia-apps/blob/4abc544aa97d4a2c34e7a0e7ccf3444ffd01bc9f/theia-full-docker/Dockerfile#L83

Verified on 4abc544
