### ISSUE TITLE
golang version - any plans including delve debugger?

### ISSUE THREAD

**Issue by JCzz** [theia-ide/theia-apps#118]
Do you have any plans including delve debugger for theia-go docker version?
https://github.com/go-delve/delve/releases

I am asking without knowing if it even possible to use a debugger with Theia?

**Comment by JanKoehnlein** [comment]
I answered that on Spectrum https://spectrum.chat/theia/general/how-to-know-if-a-terminal-had-completed-a-command~04883f99-bb06-4807-a8c1-3e99d4c6eff7?m=MTU0NzcxMjQ3ODE2NQ==

**Comment by akosyakov** [comment]
Debugging will be possible via running vscode-go extension: https://github.com/theia-ide/theia-apps/pull/146
