### ISSUE TITLE
[travis] docker images are cached too eagerly

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia-apps#12]
Currently, the travis file calls
```
docker build ... --cache-from "$IMAGE_TAG"
```
The image tag contains the most recent version number of `@theia/core`.
This strategy can yield stale builds when we don't update all versions of all Theia NPM packages simultaneously. Note we currently have `@theia/core` at version 0.3.0 while e.g. `@theia/languages` is at 0.3.1. 

In particular, this does not allow to produce app image builds where the version of the specific extensions change more frequently than Theia. As the Dockerfile has no changes, `yarn` won't be run.
This actually happens for `theia-go`.

**Comment by JanKoehnlein** [comment]
We should disable caching or introduce a discriminator build argument (composed from the versions of the critical extension packages) that we pass on to the Dockerfile and use it as ARG.

**Comment by JanKoehnlein** [comment]
I removed the caching for the time being.

**Comment by akosyakov** [comment]
Let's go without caching, then `docker pull` should be removed.

**Comment by akosyakov** [comment]
I am closing it. We've decided to rebuild each time.
