### ISSUE TITLE
Unable to open any file with theia-full

### ISSUE THREAD

**Issue by benoitf** [theia-ide/theia-apps#126]
$ docker run -it -p 3000:3000  theiaide/theia-full:0.3.19

creating a foo.json file, try to open it and it's not possible.
```
monaco-editor-provider.js:141 Uncaught (in promise) TypeError: Cannot read property 'getBackendOS' of undefined
    at t.e (monaco-editor-provider.js:141)
    at new t (yang-monaco-editor-provider.js:53)
    at Object.t.resolveInstance (instantiation.js:21)
    at resolver.js:72
    at Object.t.resolve (resolver.js:96)
    at container.js:319
    at e._get (container.js:310)
    at e.get (container.js:230)
    at e.editorProvider (monaco-frontend-module.ts:79)
    at e.<anonymous> (editor-widget-factory.ts:47)
```

note: it's working with minimal image 
```
docker run -it -p 3000:3000  theiaide/theia:0.3.19
```

**Comment by apupier** [comment]
it is working with theiaide/theia-full:0.3.18

**Comment by uniibu** [comment]
I can confirm that both  theiaide/theia:0.3.19 (latest) and theiaide/theia:next does not open any file. This is because of outdated `theia-yang-extension`. I made pr to fix this https://github.com/theia-ide/yangster/pull/73 so for the mean time, an alternative solution if you don't use the yang extension is to uninstall it via the extension widget.

**Comment by marcdumais-work** [comment]
For the immediate issue at hand, I propose we remove `theia-yang-extension` from the full image. See PR #127. I confirmed this fixes the file opening issue.

Presumably the `yangster-docker` image would be affected as well? This strategy will not work in that case.

**Comment by JanKoehnlein** [comment]
I am on it. I'll create a new yangster release within two hour.

**Comment by JanKoehnlein** [comment]
Fixes applied to `yangster@next` and `yangster@latest`. Build is running. Will check once it's finished.

**Comment by JanKoehnlein** [comment]
Both `theiaide/theia-full.next` and `theiaide/theia-full.latest` are working again. 

Thanks for reporting and sorry for the trouble this has caused.
