### ISSUE TITLE
Stuck at Theia Preload when using nginx proxy

### ISSUE THREAD

**Issue by Emporea** [theia-ide/theia-apps#129]
![image](https://user-images.githubusercontent.com/21969523/52453689-c8527e80-2b48-11e9-9db4-cc512b0c9892.png)

i am stuck at this loading screen when i am trying to connect via nginx proxy.
My config is:

```
server {
listen 80;
listen [::]:80;
       server_name www.example.tld;
        root /var/www/html/www.example.tld;
        index index.html;

        location / {
            proxy_pass http://localhost:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            client_max_body_size 0;
            add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
            add_header Referrer-Policy "same-origin" always;
            access_log /var/log/nginx/code.access.log;
            error_log /var/log/nginx/code.error.log;
        }
}
```

when connection via ip or domain and port it works ( www.example.tld:3000 )

**Comment by krd78** [comment]
Hello, i have the same issue... I tried to do same as https://github.com/theia-ide/theia/issues/2650 but not working for me. Tell me if this link helped you !

**Comment by marechal-p** [comment]
Looking at [this comment](https://github.com/theia-ide/theia/issues/2650#issuecomment-416671826), their configuration seems a bit different from what you have here.

My guess is that the protocol upgrade is not going through (HTTP(S) to WS(S)), because you seem to be able to fetch most resources (theme/css, spinner, maybe others...) but you are stuck loading, which means it could be an issue with the websockets.

I would recommend investigating in your browser with the network panel of the devtools, to check what exactly is failing, maybe some errors in the console would help you too.

**Comment by krd78** [comment]
I solved it ! it misses the next :
(before server in config)
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
```
(in server in config)
```
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
```

**Comment by samos667** [comment]
Somebody have the vhost conf for apache ?

**Comment by IceWreck** [comment]
Having the same issue on apache, how do I fix it?

**Comment by Emporea** [comment]
> 
> 
> Having the same issue on apache, how do I fix it?

I dont know, but i switched to a opensource variant of VSCode.
https://github.com/cdr/code-server
Give it a try if you want. Had no issues with that.

**Comment by IceWreck** [comment]
I actually fixed it. We had to allow websockets to pass through.

```
<VirtualHost *:80>
  ServerName example.com

  ProxyPreserveHost On
  ProxyRequests Off
 
  # allow websockets
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://127.0.0.1:8020/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://127.0.0.1:8020/$1 [P,L]

  # Proxy 
  ProxyPass / http://127.0.0.1:8020/
  ProxyPassReverse / http://127.0.0.1:8020/


</VirtualHost>

```

**Comment by samiy803** [comment]
I have been trying to get it to work for an hour now. Your method works, thank you!
