### ISSUE TITLE
Clean Yarn cache from Docker image

### ISSUE THREAD

**Issue by deboer-tim** [theia-ide/theia-apps#14]
The Theia docker image is pretty big. When I dug into it, there's 335Mb in the Yarn cache that is pulled in during build and then never used again. I've found some other projects that have added "&& yarn clear cache" to their docker builds, which would clean this up and reduce the image size by 335Mb.

Also noticed the --production=true flag while I was investigating this, not sure if that would speed up the build or remove unnecessary dependencies too.

**Comment by hexa00** [comment]
Sounds like a good idea to do this... --production will not install devDependencies which should be OK.

**Comment by akosyakov** [comment]
It should work if we install `@theia/cli` as a global node module instead of a dev dependency.

It could be worth to investigate [yarn autoclean](https://yarnpkg.com/en/docs/cli/autoclean) for this matter as well.

**Comment by akosyakov** [comment]
RFC to avoid using yarn cache: https://github.com/yarnpkg/rfcs/pull/53 - discussed how to work it around for different cases

**Comment by akosyakov** [comment]
I've tried to remove `@theia/cli` from dev dependencies, but it is not so straightforward:
- `theia build` does not work from global modules, `webpack` cannot be resolved for some reasons
- and we use `theia start` to start the app

To use `--production` flag these issues should be resolved first.

**Comment by akosyakov** [comment]
We've managed to reduce the size of `theiaide/theia` significantly by:
- using the alpine image as the base image: https://github.com/nodejs/docker-node#nodealpine
- removing electron dependencies
- get rid of build tools like python and make using the separate build stage: https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds

Docker file is here: https://github.com/theia-ide/theia-apps/blob/master/theia-docker/Dockerfile
