### ISSUE TITLE
Can not edit file by default in Ubuntu

### ISSUE THREAD

**Issue by heyfluke** [theia-ide/theia-apps#169]
See this gist https://gist.github.com/heyfluke/b8372df866ec2584f9a51ca7d7fe9ebb

**Comment by marcdumais-work** [comment]
Hi @heyfluke ,

Thanks - nicely written guide. If I understand correctly, this would potentially help users who want to run Theia in Docker locally (or on a host they control), in a way that avoids permission issues when creating/modifying files from a host volume? 

I noted there may be a limitation to the suggested method: I do not see my "work" (LDAP user with high uid) user listed in `/etc/subuid` / `/etc/subgid`, though I see my local test accounts.
