### ISSUE TITLE
[electron] language servers not started / supported

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#173]
**Description**

The language servers don't appear to be started correctly in the bundled electron version, resulting in missing language features, and textmate grammars.

**Steps to reproduce**
- `cd theia-electron`.
- `yarn`.
- `yarn package` or `yarn package:preview`.
- start the application.
- open a typescript file (`.ts`), notice that there is no language support (features & coloring/highlighting).

**Additional Information**

Tested with: macOS, Ubuntu and Windows.

![image](https://user-images.githubusercontent.com/40359487/56743616-e80b4300-6744-11e9-901e-c1fc452ed6e2.png)

**Comment by akosyakov** [comment]
cc @kittaakos

**Comment by kittaakos** [comment]
> * bundled theia electron application

Do you have a `package.json`?

**Comment by kittaakos** [comment]
> and textmate grammars.

You have to add the TextMate grammar extension to your application; I am ignoring this issue.

I am checking the `node Perhaps it is not on the PATH` problem.

**Comment by kittaakos** [comment]
> I am checking the `node Perhaps it is not on the PATH` problem.

It worked for me:
```diff
diff --git a/theia-electron/package.json b/theia-electron/package.json
index 7f9b63b..07c5629 100644
--- a/theia-electron/package.json
+++ b/theia-electron/package.json
@@ -56,6 +56,7 @@
         "@theia/task": "next",
         "@theia/terminal": "next",
         "@theia/typescript": "next",
+        "@theia/textmate-grammars": "next",
         "@theia/userstorage": "next",
         "@theia/workspace": "next",
         "typescript": "latest"
```

**Comment by vince-fugnitto** [comment]
> > I am checking the `node Perhaps it is not on the PATH` problem.
> 
> It worked for me:
> 
> ```diff
> diff --git a/theia-electron/package.json b/theia-electron/package.json
> index 7f9b63b..07c5629 100644
> --- a/theia-electron/package.json
> +++ b/theia-electron/package.json
> @@ -56,6 +56,7 @@
>          "@theia/task": "next",
>          "@theia/terminal": "next",
>          "@theia/typescript": "next",
> +        "@theia/textmate-grammars": "next",
>          "@theia/userstorage": "next",
>          "@theia/workspace": "next",
>          "typescript": "latest"
> ```

I added the `@theia/textmate-grammars` and did notice the coloring/highlighting but the bug is more than that, there is also no language support (ex: `Find All References`). It seems from the app the Typescript language server cannot be properly started.

As a side note, should we not add all the dependencies present from the main repository under `examples/electron`? For example, I believe the `@theia/textmate-grammars` should definitely be present in the app.
