### ISSUE TITLE
r.setUriThrowOnMissingScheme is not a function

### ISSUE THREAD

**Issue by dhananjayharel** [theia-ide/theia-apps#184]
When Im trying to build the docker image the editor doesnt start and console gives this error.
It seems that it vscode_uri <=1.0.6 doesn't have that method.

If we use lates vscode_uri then it brakes other things.

**Comment by marcdumais-work** [comment]
Hi @dhananjayharel ,

Which image are you building? `theia-docker`? Latest or next?

**Comment by dhananjayharel** [comment]
latest

**Comment by dhananjayharel** [comment]
any update?

**Comment by marcdumais-work** [comment]
@dhananjayharel  can you give it another try: we had a bugfix Theia release late yesterday, containing a fix for `vscode-uri` issues.
