### ISSUE TITLE
Manipulating Worspace

### ISSUE THREAD

**Issue by joecaraccio** [theia-ide/theia-apps#187]
Sorry if this is a dumb question! I was currious if there was a way to map the workspace to specific folder on the system

The default docker application seems to just create a /home/project subdirectory. Is there a way to run it so the workspace is just on the drive

**Comment by marcdumais-work** [comment]
Hi @joecaraccio ,

Yes, it's possible. One can use the `-v` docker flag, to do exactly this. There are a couple of example in the repo's main [README](https://github.com/theia-ide/theia-apps#how-to-use-theiaidetheia-image). In the examples, the current working directory on the host is mounted on `/home/project` in the container. You can use a specific folder's path if you want.

Heads-up: many experience permission issues when accessing files/folders from inside the container, that are owned by their "real" user on the host. If you do, see [here](https://github.com/theia-ide/theia-apps/issues/169#issue-435518730) for a work-around suggested by another user.
