### ISSUE TITLE
moving to theia-swift-extension

### ISSUE THREAD

**Issue by satishbabariya** [theia-ide/theia-apps#190]
In current support for swift in theia is using the unpublished vscode extension, for that in theia swift docker, we need to build vscode extension everytime. so insted of using vscode extension to Spawn langague server, use theia-swift-extension.

after publishing the extension, I'll update current theia-swift docker image and add swift support inside theia full docker image also.

here is the extension repo: [https://github.com/satishbabariya/theia-swift-extension](https://github.com/satishbabariya/theia-swift-extension)

**Comment by satishbabariya** [comment]
@marcdumais-work any suggestions on this?

**Comment by marcdumais-work** [comment]
Hi @satishbabariya ,

Nice. However it could be that the vscode extension brings more features than just the Language Server. e.g. debug and tasks to help the user with build, etc... 

So this proposed change would improve the build time, potentially at the expense of feature-fullness. Have you considered this aspect?

**Comment by satishbabariya** [comment]
Yeah,  but those things are not included in the  current vs extension i.e https://github.com/apple/sourcekit-lsp/blob/master/Editors/vscode/src/extension.ts

In future may  introduce debug and other features, but those are not current part of the sourcekit-lsp

**Comment by marcdumais-work** [comment]
@satishbabariya Sounds good then; thanks for your efforts to improve theia-swift!

**Comment by satishbabariya** [comment]
@marcdumais-work sure np.

**Comment by satishbabariya** [comment]
@akosyakov is it ok to move forward with theia-swift-extension repo in theia org?

for now, the swift-language-server(sourcekit-lsp) is already intrageted inside the swift nightly toolchain, so we can integrate the swift inside the theia-full docker images with adding only swift toolchains.

**Comment by akosyakov** [comment]
@satishbabariya yes, sure. I'm not sure about technical details, maybe @marcdumais-work can help

**Comment by satishbabariya** [comment]
@marcdumais-work any suggestions on this thread?

**Comment by marcdumais-work** [comment]
Hi @satishbabariya ,

Sorry, I missed the ping above. 

One potential way forward, to avoid re-building the VS Code swift extension every time we build the image would be for you to build and publish the .vsix on your repo's GitHub [releases tab](https://github.com/satishbabariya/theia-swift-extension/releases). It could then be fetched from there when the image is built. 

WDTY?

**Comment by vince-fugnitto** [comment]
The `theia-swift` extension is deprecated as language-specific extensions are deprecated in favor of using vscode extensions.
It is therefore not possible to use this extension as a replacement for the vscode one.
