### ISSUE TITLE
[full] how to setup for python debugger?

### ISSUE THREAD

**Issue by dejunzhou** [theia-ide/theia-apps#191]
I'm using the theia-full-docker packages, the python debugger seems not function, can someone provide a new package.json file?

**Comment by marcdumais-work** [comment]
Hi @dejunzhou ,

The Theia extension we use in `theia-full`, to support Python ([@theia/python](https://github.com/theia-ide/theia/tree/master/packages/python)), does not support debugging yet. 

One potential way forward would be to instead try to use the [corresponding VS Code extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) in Theia, that I assume is full-featured and would support debugging and other features currently missing in the current Theia extension. 

ATM the VS Code extensions compatibility in Theia is not 100%, but many extensions work out-of-the-box. 

Here's an example where we have done this, for the go image, "next" version: https://github.com/theia-ide/theia-apps/blob/master/theia-go-docker/next.package.json

**Comment by dejunzhou** [comment]
Thanks Marc, I'm currently working on turn on python debug by using https://github.com/vilkazz/theia-python-debug.

**Comment by marcdumais-work** [comment]
Hi @dejunzhou ,

Interesting. Any success so far? I had a quick look, and despite what the README says, I do not see that they are using the VS Code extension for Python.

**Comment by marcdumais-work** [comment]
Ah, I see it now; the repo includes a copy of the main Theia repo, and they've added a "python-debug` extension to the packages, that pulls and uses the VS Code extension.

**Comment by dejunzhou** [comment]
It's working for me, but not the latest release. the Next build works for me.
