### ISSUE TITLE
[java] javac is not found

### ISSUE THREAD

**Issue by nlpguyz** [theia-ide/theia-apps#192]
I launched the docker image like
`sudo docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia-java:next`

In the terminal, "javac" is not found. The path of "java" points to "jre" instead of "jdk"
theia@cccf82b4924d:/home/project$ which java
/opt/ibm/java/jre/bin/java

Can you please check if JDK is pulled in? Thanks.

**Comment by marcdumais-work** [comment]
Hi @nlpguyz ,

It looks like `javac` is part of the image, but its directory is not in the path: `/opt/ibm/java/bin/javac`. 

Another consideration is that the image we start-from, `ibmcom/ibmjava:8-sdk` is deprecated and should be replaced. But we can try for a quick fix right now for your issue.

**Comment by marcdumais-work** [comment]
PR: https://github.com/theia-ide/theia-apps/pull/193

**Comment by nlpguyz** [comment]
Thanks for your prompt response. The patch fixed the issue!
