### ISSUE TITLE
the init process in docker cause a lot of defunct processes

### ISSUE THREAD

**Issue by tom-shan** [theia-ide/theia-apps#195]
after start docker with this command:
`
docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next
`
and refresh the page, there are many zombie processes in the process list.
For now the init process(PID is 0) will not wait for it's child processes, so these child processes will not be reaped by the init and remains.
![image](https://user-images.githubusercontent.com/7686800/60560711-7cb4a180-9d83-11e9-924d-2f00a1c6da69.png)

**Comment by tom-shan** [comment]
According to https://github.com/krallin/tini, we can add a suffix of `"/tini", "--"` to the ENTRYPOINT in Dockerfile.

**Comment by marcdumais-work** [comment]
Interesting, thanks @tom-shan for reporting this issue.
