### ISSUE TITLE
Reduce size of java image

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia-apps#20]
See for the guidance: https://github.com/theia-ide/theia-apps/issues/14#issuecomment-355573827

**Comment by sr229** [comment]
Is it possible we can try OpenJDK images since we're using a more obsolete image for Java?

**Comment by vince-fugnitto** [comment]
AFAIK, the size of the Java image is still an issue.

**Comment by sr229** [comment]
@vince-fugnitto I don't think we can find a way to lower that since JDK itself is a big chonk of a SDK.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I don't think we can find a way to lower that since JDK itself is a big chonk of a SDK.

@sr229 do you propose the issue to be closed then?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I don't think we can find a way to lower that since JDK itself is a big chonk of a SDK.

Closing based on comment.
