### ISSUE TITLE
[full, cpp] clangd, clang-tidy packages not found

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#223]
Our `cpp` images are not building ATM. Looks like we need to update the clangd/clang-tidy Debian packages we pull:

```
E: Unable to locate package clang-tools-9
E: Unable to locate package clang-tidy-9
```

It might be because LLVM have switched to version 10 as the bleeding edge dev version and we need to use that one. @lmcbout mentioned that now `clangd` has it's own Debian package instead of being part of `clang-tools`, so we may need to install that new package as well. 

See build errors: 
https://travis-ci.org/theia-ide/theia-apps/jobs/577117058#L4013
https://travis-ci.org/theia-ide/theia-apps/jobs/577117072#L1433

**Comment by vince-fugnitto** [comment]
Closed in #232
