### ISSUE TITLE
Update references of 'eclipse/theia-cpp-extension'

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#227]
The repo **eclipse/theia-cpp-extension** has been moved and renamed to
 [**eclipse-theia/theia-cpp-extensions**](https://github.com/eclipse-theia/theia-cpp-extensions). We need to adjust any reference to the old org and name.

_Example_:

https://github.com/theia-ide/theia-apps/blob/9338e6498d8498719466e125e0108f95033f69ae/theia-rust-docker/Dockerfile#L23-L24

cc @dwjbosman

**Comment by dwjbosman** [comment]
Will update the reference in outstanding pull request #221

**Comment by dwjbosman** [comment]
@vince-fugnitto I am new to this and trying to grasp the structure of the theia-cpp-extensions:

Currently it uses: 

```
"adapters": {
    "cdt-gdb-vscode": "https://github.com/theia-ide/cdt-gdb-vscode/releases/download/v0.0.89/cdt-gdb-vscode-0.0.89.tgz"
  }
```

However theia-ide/cdt-gdb-vscode is a fork of eclipse-cdt/cdt-gdb-vscode

Currently upstream (eclipse-cdt) contains some very useful additions (remote debugging) which have not been merged into theia-ide. Furthermore theia-ide does not seem to have made any changes to the upstream version (except for some release tags). Why does the theia-cpp-extensions make use of the fork instead of the upstream variant?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I am new to this and am trying to grasp the structure of the theia-cpp-extensions:
> 
> Currently it uses:
> 
> ```
> "adapters": {
>     "cdt-gdb-vscode": "https://github.com/theia-ide/cdt-gdb-vscode/releases/download/v0.0.89/cdt-gdb-vscode-0.0.89.tgz"
>   }
> ```
> 
> However theia-ide/cdt-gdb-vscode is a fork of eclipse-cdt/cdt-gdb-vscode
> 
> Currently upstream (eclipse-cdt) contains some very useful additions (remote debugging) which have not been merged into theia-ide. Furthermore theia-ide does not seem to have made any changes to the upstream version (except for some release tags). Why does the theia-cpp-extensions make use of the fork instead of the upstream variant?

Perhaps @marechal-p can shed some light.
cc @marcdumais-work

**Comment by marechal-p** [comment]
> Furthermore theia-ide does not seem to have made any changes to the upstream version (except for some release tags). Why does the theia-cpp-extensions make use of the fork instead of the upstream variant?

The `theia-ide` fork exists for the release tags, since upstream wasn't really published anywhere.

We can see to uplift sometime soon :)

**Comment by vince-fugnitto** [comment]
For additional information, the `theia-cpp-extension` repository has recently been published to npm (`@theia/cpp-debug`), so there is no longer a need to have to clone the repo and build within the Dockerfile any longer.

**Comment by dwjbosman** [comment]
Thank you for the update, I'll have a look at it.

**Comment by vince-fugnitto** [comment]
@dwjbosman I don't believe there is anything to do on your side, I don't see the cloning and build any longer in the `rust` image. I have the PR #258 which addresses other instances.

**Comment by marcdumais-work** [comment]
Hi @vince-fugnitto 

I created a follow-up issue: #264
