### ISSUE TITLE
Have preferences setting to standardize the code format

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia-apps#233]
Since there is more than one person editing the files for the theia-apps, we should have a template for the save. If the default "auto-save = on" and "auto-format = on" in vscode, the code should be saved according to the rules defined for the project. So in ".vscode/settings.json", we can add preferences on how the code should looks like by adding preferences like in the main theia repo:

```json
 {
    "editor.insertSpaces": true,
    "[typescript]": {
        "editor.tabSize": 4
    },
    "[json]": {
        "editor.tabSize": 2
    },
    "[jsonc]": {
        "editor.tabSize": 2
    },
}
```

**Comment by vince-fugnitto** [comment]
@lmcbout is it something you're working on?

**Comment by lmcbout** [comment]
@vince-fugnitto not now, you can take it if you want

**Comment by marcdumais-work** [comment]
@vince-fugnitto that would be a low priority.
