### ISSUE TITLE
Started work on Theia and Ada

### ISSUE THREAD

**Issue by dwjbosman** [theia-ide/theia-apps#237]
I am trying to setup a Docker file to implement Ada support in Theia (see theia-ada branch)

There is a project https://github.com/AdaCore/ada_language_server which implements a Visual Code plugin for the language server. After some hacking I have been able to install FSF GNAT and compile all the required libraries. 

Currently I am not sure how to install the Visual code plugin (located in https://github.com/AdaCore/ada_language_server/tree/master/integration/vscode/ada) in Theia. Can anyone help out?

**Comment by marcdumais-work** [comment]
> Currently I am not sure how to install the Visual code plugin (located in https://github.com/AdaCore/ada_language_server/tree/master/integration/vscode/ada) in Theia. Can anyone help out?

Hi @dwjbosman ,

From the look of it, the directory you reference probably contains an un-packaged vscode extension. It does not seem to be published to the VS Code marketplace either. Maybe it's in very early development? 

I see two approaches:
- build a package from it yourself. Normally the `vsce` tool is used, but there may be missing bits/configs : https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions
- try to use it as-is: In your application's [plugins folder](https://github.com/theia-ide/theia-apps/blob/master/theia-go-docker/Dockerfile#L72) create a sub-directory and copy-over all the content from the `integrations/vscode/ada` folder. But I an not sure if that will be enough - there may be an expected structure to what an "unzipped" VS Code extension looks like, and expected configs, etc. 

Note: I notice that this repo, including the language extension, is licensed under GPL v3 - it may make it less likely to be adopted in general - a lot of companies will prefer not using it given that there is some uncertainty about how "GPL virality" spreads to other components in the JS/TS world. 

OTOH if an ADA extension had a permissive licence and used an external component that's licensed under GPL, that would be ok.

**Comment by dwjbosman** [comment]
Thank you for the pointers. I will have a look at it.

**Comment by vince-fugnitto** [comment]
Closing the issue as it is quite old and there has not been any activity for a while.
