### ISSUE TITLE
use vscode extensions instead of native

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia-apps#239]
It should be done for:
- java
- java-debug
- nodejs-debug

We are going to delete these native extensions. Motivated by https://github.com/eclipse-theia/theia/pull/6113#issuecomment-528782824

@marcdumais-work Do we need also an issue in the theia repo?

**Comment by vince-fugnitto** [comment]
Closing thanks to https://github.com/theia-ide/theia-apps/pull/287
