### ISSUE TITLE
Reduce theia-full image size

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia-apps#24]
Clean yarn cache as remove electron as in the theia-docker image

**Comment by vince-fugnitto** [comment]
It looks like the removal of the `yarn cache` is currently handled in the `theia-full-docker` image :)
I'll close the issue.

https://github.com/theia-ide/theia-apps/blob/4abc544aa97d4a2c34e7a0e7ccf3444ffd01bc9f/theia-full-docker/Dockerfile#L162-L163
