### ISSUE TITLE
[travis] the 'theia-full-docker' image should be tested when no images are tested

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#246]
**Description**

With the introduction of PR #236, only images which have changes are built and tested during CI. I propose that if a PR introduces changes that do not directly affect any image, that the base `theia-full-docker` image is at least tested.

At the moment, this is not the case: #245 - [travis results](https://travis-ci.org/theia-ide/theia-apps/builds/590554565?utm_source=github_status&utm_medium=notification)

@dwjbosman is this something you'd like to handle?

**Comment by dwjbosman** [comment]
Ok

**Comment by vince-fugnitto** [comment]
Closed by #247
