### ISSUE TITLE
[theia-go-docker] using "next" versions results in a non-starting application

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#26]
IIUC, using "latest" version in package.json means that we will pick-up the latest published version of each module. In theory we can instead use "next" which means (I think) the latest version of a given component, even if not released yet, as part of a Theia version. 

So for theia-docker-go, I tried to replace "latest" by "next" in package.json, and build the application (I by-pass docker and build natively - I assume the result would be the same with Docker). 
$> cp latest.package.json package.json
$> # replace all "latest" by "next" in package.json
$> yarn
$> npx theia build
$> node src-gen/backend/main.js 

The application builds correctly but there's an issue reported in the frontend, preventing it from starting: 

![image](https://user-images.githubusercontent.com/25749063/34720952-c3373f10-f50e-11e7-800d-0aad655e6d15.png)

Should this work? I guess by using "next" we might end-up with a mis-match of Theia extensions that are not tested well together? 

If instead I keep the content of the original "latest.package.json", then the application starts correctly.

**Comment by akosyakov** [comment]
We've removed next version for go because the go extension is not compatible with next version of Theia extensions.

**Comment by marcdumais-work** [comment]
Thanks. Anyone knows why the go extension is not compatible with the next version of Theia extensions?

**Comment by akosyakov** [comment]
because it uses `^0.3.0` as a version for Theia extensions, which does not include `0.4.x` (next)

**Comment by marcdumais-work** [comment]
ok, thanks @akosyakov
