### ISSUE TITLE
Any Idea how to connect to MySQL Docker?!

### ISSUE THREAD

**Issue by MarcoGriep88** [theia-ide/theia-apps#261]
Hi there,

can anyone help me with conneting to mysql docker database in my sourcecode running inside of theia-python? I can not find the mysql docker host or ping it... I tried to link those two docker container by starting theia like this:

docker run --name=meinestadtdb -d mysql/mysql-server:latest
docker run -it --init -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia-full:next --link meinestadtdb:db

i can either ping "meinestadtdb" nor "db". Should this not be the hostname of the MySQL Database Container?!

**Comment by marcdumais-work** [comment]
Hi @MarcoGriep88,

I have never tried something like this, but it seems that `docker --link` is considered a legacy feature: https://docs.docker.com/network/links/

Docker networks seems to be the suggested way to do this now: https://docs.docker.com/network/

Maybe you would have better luck with this one
