### ISSUE TITLE
[full] Setup THEIA_DEFAULT_PLUGINS so we can use plugins

### ISSUE THREAD

**Issue by Hartick** [theia-ide/theia-apps#263]
Hi! I wondered if I can install a VSCode extension on theia-full.
I've tried to install liveshare extension but i can't, because the plugins folder where I can put .vsix  doesn't exist, but considering that we are in a container the folder persistence is low.  

What is the right way to install a VSCode extension?

**Comment by marcdumais-work** [comment]
Hi @Hartick ,

No, I do not think so, with the current image. I am not sure if the liveshare VS Code extension works in Theia, but for any VS Code extension to work we'll need a little update to the image I think: set environment variable `THEIA_DEFAULT_PLUGINS` to point to a `plugins` folder, before starting the Theia backend. 

I would do this little change right now, but we have an issue ATM with some golang modules not installing/building, preventing the image from successfully building/publishing.

**Comment by marcdumais-work** [comment]
We need to do something like: 
https://github.com/theia-ide/theia-apps/blob/master/theia-go-docker/Dockerfile#L71-L72

**Comment by marcdumais-work** [comment]
@Hartick I did a quick fix for the build and also set environment variable `THEIA_DEFAULT_PLUGINS`. I picked folder `/home/theia/plugins` for plugins -  you can put your VS Code extension(s) there. 

If you build your images yourself you can rebuild from the latest master. If you consume the image from dockerhub, it should be published shortly, once [CI](https://travis-ci.org/theia-ide/theia-apps/builds/609350745?utm_source=github_status&utm_medium=notification) is done.

**Comment by marcdumais-work** [comment]
BTW, work is being done on a better solution, that will permit managing VS Code extensions / Theia plugins, without the user having to manually put them in or remove them from a `plugins` folder. 

One impediment is that Microsoft does not legally allow non-VS Code products to interface with their marketplace, nor to host one's own marketplace based on their code. The following proposed Eclipse Foundation project will soon lift that limitation by providing an open-source registry for VS Code extensions and (tentatively) running a public instance at the Foundation as well: 

https://projects.eclipse.org/proposals/eclipse-extension-registry
