### ISSUE TITLE
[readme] update 'readme' to better reflect repository

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#269]
**Description**

The current information present in the `readme` is a little misleading or simply not expressive enough about the description of the repository. We should update the readme to better reflect the repository. For instance, only the `theiaide/theia` image is referenced (along with it's badge).
Some notable improvements can include:

- a better overall description
- additional badges
- additional useful links
- link to the org under [dockerhub](https://hub.docker.com/u/theiaide) (which contains the list of images)
- information regarding Electron apps
- information regarding VS Code plugin support

**Comment by Twonki** [comment]
+1 

I'd also love to see a short explanation why there is "theia-java" and "theia", and what they do, and how you choose which one is best. 

It becomes clearer once you've look at them, but I think it should be in the read me.

**Comment by marcdumais-work** [comment]
Hi @vince-fugnitto ,

It would be good to add some info about the frequent permission issues that users face when using a workspace that mounted in their container as a docker volume ( `-v "$(pwd):/home/project:cached"`).  There is no generic solution to avoid this, AFAIK, but we can at least give a heads-up in the readme.
