### ISSUE TITLE
.

### ISSUE THREAD

**Issue by leehankwang** [theia-ide/theia-apps#282]

**Comment by leehankwang** [comment]
> fff

**Comment by leehankwang** [comment]
.

**Comment by leehankwang** [comment]
Invalid registration
I can't delete because I don't have permission to delete. Sorry to bother you.

**Comment by marcdumais-work** [comment]
> Invalid registration
> I can't delete because I don't have permission to delete. Sorry to bother you.

No problem - closing it is good enough.
