### ISSUE TITLE
init fix or possible explanation

### ISSUE THREAD

**Issue by peterducai** [theia-ide/theia-apps#283]
hi all. As RHEL/Fedora guy i stopped using docker some time ago so i tried to replace docker command with podman, but running with --init it gives me error

```sh
podman run -it --init -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next
Error: please specify a path to the container-init binary
```

but when running 

> podman run -it  -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next

it starts fine and I can see IDE.

can you explain error and what --init suppose to do? thanks

**Comment by vince-fugnitto** [comment]
@peterducai I found the following information:

From the [docker](https://docs.docker.com/engine/reference/run/) documentation, it states that `--init` is used to specify the init process:
> You can use the --init flag to indicate that an init process should be used as the PID 1 in the container. Specifying an init process ensures the usual responsibilities of an init system, such as reaping zombie processes, are performed inside the created container.

> The default init process used is the first docker-init executable found in the system path of the Docker daemon process. This docker-init binary, included in the default installation, is backed by tini.

In addition, there is an issue for **podman** which describes a similar problem as you've reported:
https://github.com/containers/libpod/issues/1670

**Comment by marcdumais-work** [comment]
@peterducai 

Please see https://github.com/theia-ide/theia-apps/pull/196 for more info about us adding `--init` switch to our documentation and what it does. 

It seems that podman needs to bundle tini or equivalent like docker, for the switch to work: https://github.com/containers/libpod/issues/4159
