### ISSUE TITLE
Theia editor state - Api

### ISSUE THREAD

**Issue by Allwin-Backya** [theia-ide/theia-apps#286]
**Description**
Is there any API to get the state of the editor. Whether the editor is opened in the browser or the editor
is closed. I need this to remove the docker container if the editor is not in the active state(if it is not being used in the browser).

**Comment by vince-fugnitto** [comment]
There is definitely APIs which can give such information, mainly from the `EditorManager`. Perhaps the issue would more appropriate to be opened under https://github.com/eclipse-theia/theia as a question (so others with similar questions can find an answer more easily). In addition, you can also post such questions under https://spectrum.chat/theia?tab=posts which is a community forum :)

**Comment by Allwin-Backya** [comment]
@vince-fugnitto 
Thank you. Can you please be more specific about the editor manager, where i could find it.

**Comment by Allwin-Backya** [comment]
@vince-fugnitto 
Thank you. Can you please be more specific about the editor manager, where i could find it.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto
> Thank you. Can you please be more specific about the editor manager, where i could find it.

Sure, https://github.com/eclipse-theia/theia/blob/master/packages/editor/src/browser/editor-manager.ts

**Comment by Allwin-Backya** [comment]
@vince-fugnitto
I need to get the editor status with the help of the container id. These operation i will be performing in back end. Is there anything that could help me with this.

**Comment by marcdumais-work** [comment]
@Allwin-Backya Relatively few committers monitor this repo here. You'd potentially have better luck if you ask on our [Spectrum channel](https://spectrum.chat/theia?tab=posts), where most of the community hangs-out or opening an issue on the [main Theia repo](https://github.com/eclipse-theia/theia).

Closing this issue since it's not related to the applications in this repo.
