### ISSUE TITLE
Build error when trying to build example on OSX

### ISSUE THREAD

**Issue by wubdub** [theia-ide/theia-apps#289]
Following the build instructions after cloning from master (is that the most stable branch) on OSX:

```
$ yarn --ignore-engines
yarn install v1.21.1
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@13.7.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v13.7.0/node-v13.7.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.7.0/node-v13.7.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v13.7.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v13.7.0/SHASUMS256.txt
13.7.0
gyp info ok 
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-cae5b53a-a115-4838-8513-4a22037517f6 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-cae5b53a-a115-4838-8513-4a22037517f6 > @theia/cli > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-cae5b53a-a115-4838-8513-4a22037517f6 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-cae5b53a-a115-4838-8513-4a22037517f6 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-cae5b53a-a115-4838-8513-4a22037517f6 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-cae5b53a-a115-4838-8513-4a22037517f6 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-cae5b53a-a115-4838-8513-4a22037517f6 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
[8/17] ⠐ nsfw
[10/17] ⠐ drivelist
[7/17] ⠐ native-keymap
[9/17] ⠐ @theia/node-pty
error /Users/XX/ext/theia/node_modules/native-keymap: Command failed.
Exit code: 1

make: *** [Release/obj.target/keymapping/src/keyboard_mac.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/XX/ext/theia/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.7.0/bin/node" "/Users/XX/ext/theia/node_modules/.bin/node-gyp" "rebuild"
```

**Comment by vince-fugnitto** [comment]
@wubdub thank you for reporting the issue, can you perhaps provide additional information?
Which image in [theia-apps](https://github.com/theia-ide/theia-apps) were you attempting to build when you reproduced your problem?

**Comment by vince-fugnitto** [comment]
It is likely you are missing the following prerequisite:
```bash
xcode-select --install
```

**Comment by wubdub** [comment]
Thanks for the quick response!

So I'll admit up front I am a bit confused by the docs. I played with Theia in the the Gitpod demo and it was great so I was trying to build it locally into an executable so I could run it with my own Python code on my OSX laptop. Ultimately I would like to run Theia on a server and then connect to it via my browser to work on Python code hosted on the server. 

> Which image in theia-apps were you attempting to build when you reproduced your problem?

I won't be able to use Docker on the server for now so I was going to build from source rather than downloading and running an image. My naive mental model is that each of the [apps](https://github.com/theia-ide/theia-apps/tree/master/theia-python-docker) are just Docker containers that you can launch an IDE out of for that particular language. I was thinking if I just built from source, I could then configure the IDE for Python?

But for testing on the desktop, I started following the instructions [here](https://theia-ide.org/docs/composing_applications).

I was running ```yarn``` from the top level Theia directory and immediately got:
```
error parent@0.0.0: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <12". Got "13.7.0"
```
A quick Google search said try ```yarn --ignore-engines``` which got me to the error above.

I just checked an ```xcode-select``` is already installed.

**Comment by vince-fugnitto** [comment]
@wubdub I understand now, it looks like you may have gotten confused as this is not actually the repository for Theia but rather this repo contains example applications (docker and electron) which are built with Theia. 

The engines tag specifies the compatible versions of `node` which should be used when building the application and it **should not be ignored**. It is put in place to enforce that a specific allowed range of `node` is accepted as it is tested, and verified. Any other version outside this range will likely have problems like you’ve experienced.

Instead, you can use something like `nvm` to install a compatible version of node so you can build successfully.

**Comment by wubdub** [comment]
Awesome thanks! I fixed my ```node``` to be the compliant version by following [this](https://apple.stackexchange.com/a/207883) I then went to ```theia/example-browser``` and launched the browser and it is now working!

Is there anything else I should do to customize this for Python (seems to be working just fine at the moment though)

Thanks again for your time!

**Comment by marcdumais-work** [comment]
Hi @wubdub ,

For future reference, look [here](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md) to find the dependencies required to build your own Theia-based applications.

> Is there anything else I should do to customize this for Python (seems to be working just fine at the moment though)

Possibly. Depending where took inspiration to select the Theia extensions that ended-up in your app's `package.json`, you might be missing some interesting ones. See [here](https://github.com/eclipse-theia/theia/blob/master/examples/browser/package.json#L17-L53) for the example app from the main repo, that has a good selection. 

Also, we are in the process of deprecating various Theia-specific language extensions, including `@theia/python`. Theia supports running VS Code extensions as-is, and so we'll take advantage of that and use these, wherever possible/practical/permitted by license. Look [here](https://marketplace.visualstudio.com/items?itemName=ms-python.python) for an overview of that we'll soon have for Python - it should be a nice upgrade. 

There are a couple of technical issues that prevent us from updating the example applications in this repo here to use VS Code extensions, but we should start in a week or so. So watch what happens here and eventually you can take inspiration to do the same with your own app.
