### ISSUE TITLE
TypeScript LS not starting

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#29]
Probably happens in all images that include ```@theia/typescript```. Looks like the TS compiler is not found (tsserver). 

Generic message shown in Theia client: "Failed to start language server 'TypeScript'"

in client console:
```
messages.js:46 Uncaught (in promise) Error: Request initialize failed with message: Couldn't find 'tsserver' executable
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at main.js:242
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```

**Comment by marcdumais-work** [comment]
It's on [purpose](https://github.com/theia-ide/typescript-language-server/issues/29#issuecomment-372150882) that the TS compiler is not bundled with the LS. 

So we can instead install it globally in the docker images that need it.

**Comment by svenefftinge** [comment]
Yes, but still the message should be improved and signaled to the user, with information on what to do (install typescript)

**Comment by sr229** [comment]
workaround here is to install typescript on the runlevel container

**Comment by marcdumais-work** [comment]
Fixed by https://github.com/theia-ide/theia-apps/commit/7ad85722760cc953b6fe759485900e7c2ac36d2e
