### ISSUE TITLE
rust: update images to use vscode builtin and external extensions

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#310]
**Description**

The `theia-rust` images should be updated to use vscode builtin and external extensions.
Dependencies which are soon-to-be-deprecated should be removed as well.

One can follow the example from [theia-go](https://github.com/theia-ide/theia-apps/pull/296).

**Comment by emdfonseca** [comment]
The vsx-registry dependency will be added with #325 but rust image is now excluded from CI.

**Comment by emdfonseca** [comment]
Hi @vince-fugnitto, I believe this issue can be closed. Fix in PR #343 which is already merged.

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto, I believe this issue can be closed. Fix in PR #343 which is already merged.

Thank you!
