### ISSUE TITLE
[full] docker build error

### ISSUE THREAD

**Issue by HuangJunjia** [theia-ide/theia-apps#313]
yarn install faild
System: CentOS 7
Dokcer version: Docker version 18.03.1-ce, build 9ee9f40
Theia vesion: latest

Error messages:
```
error Could not write file "/home/theia/yarn-error.log": "ENOSPC: no space left on device, write"
error An unexpected error occurred: "ENOSPC: no space left on device, copyfile 'ycache/v4/npm-@theia-debug-0.15.0-bff955741fd0544c7c065414f3a379c38e138176/node_modules/@theia/debug/src/browser/style/breakpoint-function-unverified.svg' -> '/home/theia/node_modules/@theia/debug/src/browser/style/breakpoint-function-unverified.svg'".
```

**Comment by vince-fugnitto** [comment]
Thank you for the issue @HuangJunjia!

The error message and the fact that [CI](https://travis-ci.org/theia-ide/theia-apps/builds/654717677?utm_source=github_status&utm_medium=notification) successfully passed for both `theia-full:latest` and `theia-full:next` leads me to believe that this is a generic Docker issue regarding storage space.

The following command [`docker system prune`](https://docs.docker.com/engine/reference/commandline/system_prune/) might be useful for you as it removes any unused data and even dangling images to regain space.

You can also take a look into the Docker community and past questions on how to resolve the issue:
- https://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device
- https://forums.docker.com/t/docker-no-space-left-on-device/69205
- https://success.docker.com/article/no-space-left-on-device-error

**Comment by HuangJunjia** [comment]
Thank you so much @vince-fugnitto !
