### ISSUE TITLE
Run | Debug codelens not working with powershell in theia-java-docker

### ISSUE THREAD

**Issue by littleskoni** [theia-ide/theia-apps#314]
Hi, i try to build the theia-java-docker and run in my windows machine. I set the THEIA_SHELL to use powershell. But when try to click on the Run option, the command won't run in java process console. 

![screenshot](https://user-images.githubusercontent.com/61177786/75315932-03803680-589f-11ea-89ab-a1ec89710592.png)

Is there any configurations available to make this work?

**Comment by marcdumais-work** [comment]
Hi @littleskoni ,

Unfortunately we do not have the means to test or officially support these images on Windows at this time. 

Nevertheless, I found the following issue with one of the extensions we bundle, `vscode-java-debug by Microsoft`, that looks very similar to your problem: https://github.com/microsoft/vscode-java-debug/issues/708

![image](https://user-images.githubusercontent.com/25749063/75344036-b2a11b80-5867-11ea-9f82-2f057be6184b.png)

If I understand correctly, that extension does not support WSL shell, and in your case it fails to correctly escape the command for that shell, tripping on a space within a folder name. They suggest that one should use `cmd` instead, until WSL support is added. 

Alternatively, if you do not absolutely need debugging, you might try to [remove that extension](https://github.com/theia-ide/theia-apps/blob/master/theia-java-docker/latest.package.json#L94) from `package.json`, rebuild, and test if then you can at least run your program in powershell.

**Comment by marcdumais-work** [comment]
This bug as noted above ins in the `java-debug` extension. I do not think we can do anything about it.
