### ISSUE TITLE
add javascript/node.js development environment docker app

### ISSUE THREAD

**Issue by realies** [theia-ide/theia-apps#322]
with common extension such as eslint and prettier

**Comment by vince-fugnitto** [comment]
> with common extension such as eslint and prettier

@realies such an image exists already https://github.com/theia-ide/theia-apps/tree/master/theia-docker with support for `eslint`. You can modify it for your use-case to include the extensions you require (prettier).

**Comment by realies** [comment]
@vince-fugnitto, is there an established way to configure required extensions during container launch time?

**Comment by vince-fugnitto** [comment]
As mentioned on [Spectrum](https://spectrum.chat/theia/general/theia-chat~170dbeb6-4c13-4050-8c00-a095248fd8f0?m=MTU4NTA4MjE4OTU3OA==), adding additional extensions to images can be done by adding them directly in the `package.json` under the `theiaPlugins` property.

**Comment by vince-fugnitto** [comment]
Closing since an image already exists for TS/JS development.
