### ISSUE TITLE
include @theia/vsx-registry extension in images to allow installing extensions from Open VSX Registry

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia-apps#325]

**Comment by emdfonseca** [comment]
I can create a PR for this one. However, I realised there are a lot of apps. Not knowing what they are all about should I blindly add the @theia/vsx-registry to every app or are there a few that should be left without the vsx-registry package?

**Comment by marcdumais-work** [comment]
> However, I realised there are a lot of apps. Not knowing what they are all about should I blindly add the @theia/vsx-registry to every app or are there a few that should be left without the vsx-registry package?

Maybe limit the update to those images that are included in CI? 
https://github.com/theia-ide/theia-apps/blob/master/.travis.yml#L21-L39
