### ISSUE TITLE
docker run fails because percentage sign is not resolved

### ISSUE THREAD

**Issue by 1kastner** [theia-ide/theia-apps#332]
I tried to run theia as a docker image as it is described in the readme.
So it opened the PowerShell (which is I think the default command line for Windows) and copied line.
For some reason, the percentage sign was not resolved

```
PS C:\Users\XXX> docker run -it --init -p 3000:3000 -v "%cd%:/home/project:cached" theiaide/theia:next
Unable to find image 'theiaide/theia:next' locally
next: Pulling from theiaide/theia
aad63a933944: Pull complete
17551d40f9c7: Pull complete
1d4f35a66b6c: Pull complete
d4192b8fc2e1: Pull complete
4dda91c68cf9: Pull complete
af73feffc057: Pull complete
349e06e10445: Pull complete
3345427c5f33: Pull complete
Digest: sha256:6edac3eedf0e9ff221c36275170970cbe70eab10e9b55b6cb7c8cf9e474cf9ff
Status: Downloaded newer image for theiaide/theia:next
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: create %cd%: "%cd%" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
```

Anyhow, with the command line (CMD) it was possible to start it.
Is it possible to add the information to the readme how to run the container both from PS and CMD?

**Comment by vince-fugnitto** [comment]
@1kastner thank you for the issue! 
I unfortunately do not have a Windows machine in order to verify the behavior for PowerShell, so if you can do a quick fix it'd be really appreciated :)

@marechal-p perhaps you could do a quick test?
