### ISSUE TITLE
Make Theia images run on usermode

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia-apps#34]
theia images should run on user mode via ``USER`` + a ``RUN`` command that adds the user.

There are a couple of factors why it should be done like this:
- OpenShift compatibility/k8s compatibility
- this is how other Cloud IDEs like Cloud9 and Codenvy/Eclipse Che author their workspace stacks.

**Comment by sr229** [comment]
For a living draft, my [rendition of the first two images](https://github.com/sr229/theia-openshift) is a good citation.

**Comment by marcdumais-work** [comment]
Hi @sr229 ,

Sounds good. Would you be interested in submitting a pull-request to do so for our docker images in this repository? I would limit the scope that that alone, however. Other improvements can be tackled in their own PR. But feel free to propose other improvements separately.

**Comment by sr229** [comment]
will make a PR real soon for this images

**Comment by JamesDrummond** [comment]
@sr229 @marcdumais-work Think this is related to https://github.com/theia-ide/theia-apps/pull/41

**Comment by sr229** [comment]
yep but gonna some tweaks before clearing it off
