### ISSUE TITLE
[all] clean-up resolutions block

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#342]
The apps in this repo pretty much have the same `resolutions` block (in `latest|next.package.json`). Testing quickly, I beleive that the following entries are no longer required and could be removed:

```
"vscode-languageserver-protocol": "3.15.0-next.9"
"vscode-languageserver-types": "3.15.0-next.5"
```

**Comment by vince-fugnitto** [comment]
The resolutions were cleaned up successfully :+1: 
The only resolution present is `fs-extra` for `electron`:

https://github.com/theia-ide/theia-apps/blob/a54aaa676e3db07d22ab75dde9f3447576135b4d/theia-electron/package.json#L79-L81
