### ISSUE TITLE
Typing in active tab sometimes types in other file

### ISSUE THREAD

**Issue by jarodium** [theia-ide/theia-apps#344]
Hello,

Sometimes, when we are editing one or more files, we switch to other tab and start typing. Somehow it hangs and starts typing in the previous active tab, also, when the file is not saved.

Is anyone else experiencing the same issue? This has happened with previous versions, so I take it that this issue is somewhat old.

**Comment by vince-fugnitto** [comment]
Thank you for the issue @jarodium, I have experienced the issue intermittently in the past (mostly when editing preferences). There is an issue [upstream](https://github.com/eclipse-theia/theia/issues/7566) tracking the problem so I'll close the issue here.
