### ISSUE TITLE
[latest][cpp] switch to vscode-clangd language client

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#349]
Follow-up to https://github.com/theia-ide/theia-apps/pull/348 . After April's Theia release we can update the `latest` version of this app to also use `vscode-clangd`.

**Comment by vince-fugnitto** [comment]
The `theia-cpp:latest` image still needs to be updated to use `vscode-clangd`.

**Comment by vince-fugnitto** [comment]
The following pull-request looks to close it:
- https://github.com/theia-ide/theia-apps/pull/372
