### ISSUE TITLE
theia-full docker image doesn't contain php syntax highlighting

### ISSUE THREAD

**Issue by deto1986** [theia-ide/theia-apps#351]
Hi,

in the current theia-full docker image the syntax highlighting for php files isn't working and is not choosable, see screenshot:

![php missing](https://user-images.githubusercontent.com/3199863/80190702-01bfbe80-8615-11ea-8cac-2b2ed4045700.png)

Used image: theia-ide/theia-full:next

**Comment by vince-fugnitto** [comment]
@deto1986 thank you for the issue, would you like to care of updating the image, it requires the following builtin extension to be included:

https://github.com/theia-ide/theia-apps/blob/2991e3a433f031b22bc80e274f80620d1e6898e5/theia-php-docker/next.package.json#L66

**Comment by amnuts** [comment]
I added this to latest and next, but in retrospect it probably should have been only next?  Sorry if that's the case - I can correct if needs be.

**Comment by vince-fugnitto** [comment]
> I added this to latest and next, but in retrospect it probably should have been only next? Sorry if that's the case - I can correct if needs be.

I think both `latest` and `next` should be fine. Note that the CI will fail until #362 is merged.
