### ISSUE TITLE
In the electron versions, the menu seems to be broken.

### ISSUE THREAD

**Issue by owlJaeger** [theia-ide/theia-apps#353]
After compiling `theia-electron` and starting it, the menubar is mostly empty.

![image](https://user-images.githubusercontent.com/62302823/80823020-1afbd880-8bdc-11ea-9031-758d7cc59c93.png)

**Comment by owlJaeger** [comment]
Looks like it's not only a bug with the electron version. I've changed the target to 'browser' and tested again. Also is broken...

![image](https://user-images.githubusercontent.com/62302823/80829442-6cf62b80-8be7-11ea-881e-d28a445e5054.png)

**Comment by vince-fugnitto** [comment]
> Looks like it's not only a bug with the electron version. I've changed the target to 'browser' and tested again. Also is broken...
> 
> ![image](https://user-images.githubusercontent.com/62302823/80829442-6cf62b80-8be7-11ea-881e-d28a445e5054.png)

@owlJaeger what type of modifications did you make to `theia-electron`, changing the target should not be enough.

**Comment by vince-fugnitto** [comment]
I see the following error:
```
menu.ts:274 Uncaught (in promise) Error: A command with id 'workspace:removeFolder' does not exist.
    at e.get [as label] (menu.ts:274)
    at e.get [as sortString] (menu.ts:288)
    at menu.ts:210
    at Array.sort (<anonymous>)
    at e.addNode (menu.ts:202)
    at e.registerMenuAction (menu.ts:83)
    at n.updateAddRemoveFolderActions (navigator-contribution.ts:496)
    at navigator-contribution.ts:168
```

**Comment by owlJaeger** [comment]
In the package.json, I changed `target` to `browser`, ran `yarn`, `yarn theia rebuild:browser` and `yarn theia start`.

**Comment by vince-fugnitto** [comment]
The issue has been fixed upstream: https://github.com/eclipse-theia/theia/pull/7727

I confirmed that building 'theia-electron' now works successfully and the main-menu is rendered. If others want to fix the main-menu for their `latest` applications (including docker images) it is possible to use resolutions in the 'package.json' to resolve the issue:

```json
"resolutions": {
  "**/**/moment": "2.24.0"
},
```
