### ISSUE TITLE
theia-scala-docker

### ISSUE THREAD

**Issue by oswaldo** [theia-ide/theia-apps#356]
Hello all,

First of all, congratulations for the great work that is this project.

I've started experimenting with Theia and had already started working on the scala support for it in https://github.com/oswaldo/theia-apps/tree/theia-scala-docker/theia-scala-docker

My idea is checking if it is feasible to have Theia as the main IDE for scala in different versions (2 and the upcoming 3) and flavours ( jvm, js, native and native through graalvm).

Right now I can run it to have syntax support and the build plugin installed. This week I'll proceed on adding some dependencies to make native work, which I believe to be a "most complex scenario". After that, jvm and js should work out of the box.

Hopefully, the end result could be added to the list of variants in the main readme.

P.S.: I assumed there is no similar initiative yet as there was no theia-scala-docker before and I couldn't find an issue mentioning scala support.

Regards,
Oswaldo

**Comment by vince-fugnitto** [comment]
@oswaldo thank you for the kind words on the project and community! We definitely would be interested in having a **scala** example as part of the repo, it will help/serve others who share the same goal of providing rich **scala** support. 

It looks like you already have a good understanding of what you want to accomplish and support, we look forward to your upcoming pull-request :)
