### ISSUE TITLE
files.associations not working on Theia PHP docker image

### ISSUE THREAD

**Issue by joazvsoares** [theia-ide/theia-apps#357]
During my tests I have found that when I add `file.associations` to the `settings.json` file, the PHP language features are gone and the syntax highlighting stops working, the association with other extensions (.inc) to the PHP language doesn't work too.

I have tried with latest version of Theia from https://github.com/theia-ide/theia-apps/tree/master/theia-php-docker

Working without file.associations:
![image](https://user-images.githubusercontent.com/5097842/81489134-9696fe80-9248-11ea-963c-09bc2f138e5f.png)

Not working with file.associations:
![image](https://user-images.githubusercontent.com/5097842/81489144-ad3d5580-9248-11ea-800f-f143d6ed0297.png)

**Comment by vince-fugnitto** [comment]
@joazvsoares thank you for the issue, I believe the issue should be reported upstream to [eclipse-theia](https://github.com/eclipse-theia/theia) so we could better track the bug and provide a fix (the fix will ultimately be upstream). 

I found some pass issues/pull-requests which are related to the problem:
- https://github.com/eclipse-theia/theia/pull/4973
- https://github.com/eclipse-theia/theia/issues/4716
- https://github.com/eclipse-theia/theia/issues/4581

**Comment by joazvsoares** [comment]
Thank you @vince-fugnitto 
I have created an issue there https://github.com/eclipse-theia/theia/issues/7791, do you think we can close this one?

**Comment by vince-fugnitto** [comment]
> Thank you @vince-fugnitto
> I have created an issue there [eclipse-theia/theia#7791](https://github.com/eclipse-theia/theia/issues/7791), do you think we can close this one?

Thank you! Yes I'll close the issue for you here.
