### ISSUE TITLE
bug: 'theia-full' and 'theia-go' failing

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#359]
**Description**

The `theia-full` and `theia-go` images have been failing for some time (cron job) due to some errors with **golang** dependencies.

- [cron build-history](https://travis-ci.org/github/theia-ide/theia-apps/builds)
- [example error](https://travis-ci.org/github/theia-ide/theia-apps/jobs/685947389#L2209)

**Additional Information**

There have been similar errors in the past, the build has failed previously due to golang errors:
- https://github.com/theia-ide/theia-apps/issues/329
- https://github.com/theia-ide/theia-apps/issues/91

**Comment by FreakyTurtle** [comment]
Seconded, any updates on this? can't build theia-full with go as it is.

**Comment by FreakyTurtle** [comment]
Ok so I took a look at this myself.  The failure was happening at the golangci lint "go get" and i found a thread on the same issue in that repo's issues [as you can see here](https://github.com/golangci/golangci-lint/issues/1037).  It detailed the fix as using go modules, so i changed that line at 110, and ran the build locally without an issue at that stage. I'm not all that familiar with go, so please do take a look whoever this concerns... Here's my PR  #362

**Comment by vince-fugnitto** [comment]
Fixed thanks to #362 and #363
