### ISSUE TITLE
docker run - open terminal - jq not found - how do I install it?

### ISSUE THREAD

**Issue by markfirmware** [theia-ide/theia-apps#367]

**Comment by vince-fugnitto** [comment]
@markfirmware are you attempting to install [jq](https://stedolan.github.io/jq/) in your image?

Please note that the images are meant as examples, and for test purposes. If you require additional dependencies, extensions, plugins then you can use the existing images as an example to create your own specific image.

**Comment by markfirmware** [comment]
Ok, I see - thanks so much for the quick response!
