### ISSUE TITLE
Feature Request: Official Support for Authentication

### ISSUE THREAD

**Issue by XieGuochao** [theia-ide/theia-apps#375]
I think it is necessary to have an official support for authentication, either username+password or tokens.

**Comment by vince-fugnitto** [comment]
@XieGuochao I'm not sure what you mean by official support, are you proposing authentication support in the images or the framework? Please note that the images are examples for others to build their own docker images (we use these images for tests mainly). There are no plans to add authentication (such as logging in) on top.

**Comment by marcdumais-work** [comment]
Though it should be in theory possible to add authentication to one or more image, this is not a direction we're looking to go right now. Instead I would advise looking into doing this outside the images where the Theia app is running. One way is to have something like Keycloak in front of the development container, only letting it be accessed if auth passes.
