### ISSUE TITLE
[full, go] update to new go extension

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#378]
The go extension by Microsoft is moving to the go community and will change publisher (and so `id`). 

blog post: https://blog.golang.org/vscode-go
new repo: https://github.com/golang/vscode-go

**Comment by marcdumais-work** [comment]
The newly moved extension looks to be available on open-vsx.org: 
https://open-vsx.org/extension/golang/Go

**Comment by hyangah** [comment]
Should [this config](https://github.com/theia-ide/theia-apps/blob/a54aaa676e3db07d22ab75dde9f3447576135b4d/theia-go-docker/latest.package.json#L98) be updated to pick up the newer extension? I think Dockerfile, settings also need to be updated, but I am not familiar with this repo.

**Comment by vince-fugnitto** [comment]
> Should [this config](https://github.com/theia-ide/theia-apps/blob/a54aaa676e3db07d22ab75dde9f3447576135b4d/theia-go-docker/latest.package.json#L98) be updated to pick up the newer extension? I think Dockerfile, settings also need to be updated, but I am not familiar with this repo.

@hyangah correct, occurrences of `vscode-go` (across the repository) should be updated to the new link as referenced by the https://github.com/theia-ide/theia-apps/issues/378#issuecomment-684936192. The dockerfile should only be updated if there is a need to update the development environment for `go` following the new changes (although I suspect no changes are necessary to make the extension work).
