### ISSUE TITLE
next: remove deprecated '@theia/json' dependency

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#379]
**Description**

The `next` images will need to be modified to remove the `@theia/json` dependency which has been deprecated upstream:
- https://github.com/eclipse-theia/theia/pull/8112

The resolution can also be removed:
- https://github.com/eclipse-theia/theia/pull/8132

Next release we can modify the `latest` images as well.

**Comment by marcdumais-work** [comment]
We may need to add related VS Code extensions, if not present already:
https://github.com/eclipse-theia/theia/pull/8112/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R107-R108
