### ISSUE TITLE
GH API rate error

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia-apps#38]
We have too many jobs running in parallel, one GH token is not enough. We should rather use several as secrets in travis file or break down jobs to several stages to avoid running all them together.

**Comment by sr229** [comment]
Travis CI has Pipelines in Beta, this is probably what we're looking for

**Comment by sr229** [comment]
Please be reminded due to a [compromise](https://status.npmjs.org/incidents/dn7c1fgrr7ng) in `eslint-scope`, you need to refresh your NPM tokens as well
