### ISSUE TITLE
Feature Request: support split editor

### ISSUE THREAD

**Issue by aglennquicket** [theia-ide/theia-apps#382]
Let me start by saying I am very impressed with this project. I've made my development environment a Chromebook with a remote Linux server for the last year or so. This is less clunky than Eclipse Che.

I'm using the theia-docker (nodejs) example, with nodejs 11. I don't see any way to have 2 text edit windows open/visible at the same time. There are many use cases for this.

I assume that the feature is not implemented because when I give the vim command to split the screen, :vsp, I get the following error:

CommandLine: Error executing cmd=vsp. err=Error: Command with id 'workbench.action.splitEditorRight' is not registered..

**Comment by marcdumais-work** [comment]
Hi @aglennquicket ,

Thanks for the kind words. 

> Let me start by saying I am very impressed with this project. I've made my development environment a Chromebook with a remote Linux server for the last year or so.

Awesome! 

> I assume that the feature is not implemented 

Indeed, this is supported yet. This is something that would be done in the main project repo, and would become available in the example applications here, after. I found this upstream issue: https://github.com/eclipse-theia/theia/issues/6665 

As mentioned in there, it would be necessary first to permit opening the same file in two or more editors, which is not yet the case: https://github.com/eclipse-theia/theia/issues/3857

**Comment by vince-fugnitto** [comment]
@aglennquicket it is possible to have more complex layouts (thanks to drag+drop):

<div align='center'>

<img width="1544" alt="Screen Shot 2020-08-06 at 3 13 10 PM" src="https://user-images.githubusercontent.com/40359487/89572667-70590e80-d7f7-11ea-85a9-22797750a2d2.png">

</div>

The limitations are those that Marc mentioned:
- eclipse-theia/theia#6665
- eclipse-theia/theia#3857

If there are any feature requests for the framework they should ultimately be opened on the [upstream repo](https://github.com/eclipse-theia/theia) 👍
