### ISSUE TITLE
html: include 'vscode-builtin-html-language-features' builtin vscode extension

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#384]
**Description**

The goal is to include the `vscode-builtin-html-language-features` builtin vscode extension as part of the images and apps now that it is supported by the framework, and recent versions come with typescript bundled.

Motivation: https://github.com/theia-ide/theia-apps/pull/383#issuecomment-667316105

**Comment by akosyakov** [comment]
Oh, that's very important. Preference and debugging experience will degrade without it.

**Comment by vince-fugnitto** [comment]
> Oh, that's very important. Preference and debugging experience will degrade without it.

Sorry mistyped, I added `json` last month, this is to add `html`.
