### ISSUE TITLE
yangster: deprecated yangster-docker image 

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#388]
**Description**

Should the `yangster-docker` image be deprecated in favor of adding the [yanster vscode extension](https://open-vsx.org/extension/typefox/yang-vscode) to the full image?

The `yangster-docker` image uses the `@theia/languages` dependency which is deprecated and next month the image will not work anymore for both `latest` and `next` (`next` is broken at the moment).

cc @marcdumais-work @akosyakov

**Comment by vince-fugnitto** [comment]
cc @spoenemann

**Comment by spoenemann** [comment]
Yes I think it can be deprecated.
