### ISSUE TITLE
Alt+w shortcut is overridden by "match whole word" from Find/Replace

### ISSUE THREAD

**Issue by echuber2** [theia-ide/theia-apps#399]
It seems that although alt+w is supposed to close the current tab, this shortcut is held captive by the find/replace feature, mapped to its "match whole word" mode toggle.

I tried changing the "match whole word" shortcut setting to something else, and realized there doesn't seem to be a way to "unset" a given keybinding completely, only to rebind it. After rebinding it and testing alt+w again, I was able to close tabs, but it left behind a buggy empty tab with no text in it. Closing and reopening the workspace seemed to fix this.

**Comment by vince-fugnitto** [comment]
@echuber2 thank you for the report, for issues related to the framework they should be opened in the main upstream repository: https://github.com/eclipse-theia/theia.

For the rebinding or removal of keybinding rules, we respect the same behavior as present in vscode:
- https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

If you are still experiencing issues, please open the issue upstream: https://github.com/eclipse-theia/theia.
