### ISSUE TITLE
travis: macos build constantly fails

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#409]
**Description**

The macOS build on Travis fails constantly making the entire build status a failure (when viewing the build history, pull-request, cron job). It would be good to fix the issue or remove the build if possible to remedy the build status.

https://github.com/theia-ide/theia-apps/pull/407/checks?check_run_id=1102982031

```
Services are not supported on osx
```

cc @thegecko is the macos build still necessary with the separate https://github.com/eclipse-theia/theia-example repo, is it something we can fix?

**Comment by thegecko** [comment]
`theia-example` still isn't ready unfortunately.

The 403 download error you are seeing is because the build needs a valid GH_TOKEN to avoid GitHub download rate limiting.

cc @marcdumais-work

**Comment by marcdumais-work** [comment]
Gi @thegecko 

> The 403 download error you are seeing is because the build needs a valid GH_TOKEN to avoid GitHub download rate limiting.

I have attempted to add a new token last week, that seems to work for the other images. (we've disabled publishing to dockerhub until we fix the leak - working on that).

**Comment by marcdumais-work** [comment]
I've just disabled a new feature I had enabled last week, that might be causeing the issue: "Enable build config validation", that might be related to the error message we see about services not being supported on osx. Fingers crossed :)

**Comment by marcdumais-work** [comment]
(a build is already ongoing, so we may need to trigger CI again on this image to see if it helped)

BTW, here's the (Beta) feature in question: https://docs.travis-ci.com/user/build-config-validation/

**Comment by thegecko** [comment]
It's also possible the variable needed for rate limiting has to be called `GITHUB_TOKEN`, so it may be worth trying to add that.

**Comment by marcdumais-work** [comment]
> I've just disabled a new feature I had enabled last week, that might be causeing the issue: "Enable build config validation", that might be related to the error message we see about services not being supported on osx. Fingers crossed :)

This seem to have no effect. I have added `GITHUB_TOKEN` to see if it will help.

**Comment by marcdumais-work** [comment]
> It's also possible the variable needed for rate limiting has to be called `GITHUB_TOKEN`, so it may be worth trying to add that.

I think adding `GITHUB_TOKEN` to Travis did the trick: https://travis-ci.com/github/theia-ide/theia-apps/jobs/384669032

Thanks for the hint @thegecko

**Comment by vince-fugnitto** [comment]
@thegecko is it still necessary to have the last three builds now that `theia-example` is ready?

![image](https://user-images.githubusercontent.com/40359487/97745714-ab4da400-1abf-11eb-8c59-7dd5adc97bd8.png)

**Comment by thegecko** [comment]
I guess not,  however they do have different functionality
