### ISSUE TITLE
error Couldn't find a package.json file

### ISSUE THREAD

**Issue by juanremi** [theia-ide/theia-apps#424]
some montnhs ago i deployed theia-python docker in a centos server

today i tried to do it with this command in another centos server
`docker run -it -p 3000:3000 -v "/home:/home:cached" theiaide/theia-python`

but now i got this error:

```
Status: Downloaded newer image for theiaide/theia-python
yarn run v1.22.4
error Couldn't find a package.json file in "/home/theia"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

any idea to fix it?

**Comment by marcdumais-work** [comment]
Hi @juanremi ,

I think there might be an issue with the path where you mount the docker volume. In the container it will hide directory `/home/theia`, where the Theia application resides (arguably maybe not the best place to store it). 

You could instead do something like to avoid this issue:

```
docker run -it -p 3000:3000 -v "/home/<your_user>:/home/project:cached" theiaide/theia-python
```
