### ISSUE TITLE
cant see files with theia-full

### ISSUE THREAD

**Issue by juanremi** [theia-ide/theia-apps#426]
Hi,

i deployed the theia-python and theia-php in a centos server and works fine, but when i deploy the theia-full i cant see the files in the files navigatorpanel

and i got this error on the docker container logs:

```
root ERROR [hosted-plugin: 29] ApplicationInsights:CorrelationIdManager [
  Error: getaddrinfo EAI_AGAIN dc.services.visualstudio.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
    errno: 'EAI_AGAIN',
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com'
  }
]

```

this error causing i cant see the files? 

how can i fix it?

**Comment by juanremi** [comment]
i open a terminal inside theia, and i see theia is using the user theia, not the root user like on the other containers

how can i change the user in the container?

**Comment by marcdumais-work** [comment]
Hi @juanremi ,

> and i got this error on the docker container logs:
> 
> ```
> root ERROR [hosted-plugin: 29] ApplicationInsights:CorrelationIdManager [
>   Error: getaddrinfo EAI_AGAIN dc.services.visualstudio.com
>       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
>     errno: 'EAI_AGAIN',
>     code: 'EAI_AGAIN',
>     syscall: 'getaddrinfo',
>     hostname: 'dc.services.visualstudio.com'
>   }
> ]
> ```
> 
> this error causing i cant see the files?

I do not think so. I think this error is from a vscode extension trying to reach the Microsoft telemetry servers and failing. Telemetry is not enabled in the Theia application, but I understand that some vscode extensions still insist to send one message in that case, to let MS know that telemetry is disabled. So nothing to worry about, as far as I understand - it should not affect anything.

**Comment by marcdumais-work** [comment]
> how can i change the user in the container?
> 
> * i tried to add the user theia un the centos, and then add to the user theia the group of the myuserfolder, but seems not works

Do I understand correctly that you mount a folder from the host machine, inside the container (`/home/myuserfolder`), and all files in there are owned by user root, and so can be edited in Theia images where the default user is also root? 

Something to try, that might work, is to make your own image, derived from `theia-full`, where you switch the user to root. e.g.:

```dockerfile
FROM theiaide/theia-full:latest
USER root
```

```bash
$> docker build -t myTheiaFull:latest .
```
