### ISSUE TITLE
Yarn v2 bump?

### ISSUE THREAD

**Issue by cyrilcros** [theia-ide/theia-apps#432]
Hi,
Could you please bump yarn to 1.21 or higher in your images? I am trying to use it inside the theia-full Docker image with a yarn pnp enabled project. Sadly, this bug prevents me from doing so: https://github.com/yarnpkg/yarn/issues/7642
I tried building a new Docker image from your Dockerfile and got the following error: “Step 18/58 : ADD $version.package.json ./package.json
ADD failed: stat /var/lib/docker/tmp/docker-builder190942786/latest.package.json: no such file or directory“

**Comment by vince-fugnitto** [comment]
@cyrilcros please feel free to provide a pull-request to update the `yarn` environment version in the images.

**Comment by vince-fugnitto** [comment]
I see you've updated the title to `berry v2 yarn`, unfortunately it is not yet supported by the upstream framework:
- https://github.com/eclipse-theia/theia/issues/7062

**Comment by cyrilcros** [comment]
Thanks for your very fast replies, I guess I will just submit tonight a pull request with an updated ‘classic’ yarn version.
