### ISSUE TITLE
Web Theia stucks opening big file (around 25MB)

### ISSUE THREAD

**Issue by davide-sergi** [theia-ide/theia-apps#438]
We have a Theia web application instance deployed in a remote server of our intranet. 
When we try to open a big file (25MB):
- Click on big file icon in the project explorer
- Service worker send a "readFileStream" request via JsonRPC (on the websocket)
- Service worker receives chunk messages "onFileStreamData" (on the websocket)
- After sometime websocket is closed and reopened, stopping definitely the download process
- Then, by clicking on other file icon, the related editor window is not opened 
![image](https://user-images.githubusercontent.com/56077774/98842820-6542f980-244a-11eb-9a62-163359564fe5.png)

By trying to run theia locally (on localhost) all work fine. Could be an issue related to slow downlaod speed? There are some timeout in frontend and/or backend part that trigger a websocket closing and reopening ?

**Comment by marcdumais-work** [comment]
@davide-sergi can you confirm if you saw anything suspicious in either the browser console or backend console log? 

I think we've relatively recently added configurable support to prevent opening huge files. I am thinking this may be getting in the way. IIRC there's a preference for it - maybe try to see what it's set at for the app that fails.

**Comment by davide-sergi** [comment]
I checked `.theia/settings.json` file, and there are not particular "critical" settings.
![image](https://user-images.githubusercontent.com/56077774/98921901-1b9df180-24d2-11eb-8cb0-c17984e382f8.png)

Anyway I don't think that this issue could be related to a configuration aspect. Because same scenario happens by using `vs-code/python` extension, installed as plugin in this instance of Theia.
In fact, when I try to open a jupyter notebook:
-  Click on `.ipynb` file icon in the project explorer
- `vscode-python` plugin starts rendering process for jupyter notebook (to get its tipical nice UI)
- for rendering, plugin starts dowloading of `index_bundle.js` file (around 25MB in size) from Theia BE
  - plugin sends a *fake* HTTP `GET /<path-to-file>/index_bundle.js` to the `service_worker.js`
  - `service_worker` starts download on the websocket as described above
- After sometime websocket is closed and reopened, stopping the download process
- Then - I think - `vscode-python` plugin has the logic to restart the download on the new websocket 
- This proces goes in loop ...

![image](https://user-images.githubusercontent.com/56077774/98649474-ec537d00-2337-11eb-948e-756a26130ac7.png)
![image](https://user-images.githubusercontent.com/56077774/98923086-80a61700-24d3-11eb-9974-6bb0780b7efb.png)

**Comment by davide-sergi** [comment]
As assumed what we faced was an issue related to a timeout set on the Theia backend server (and not front-end).
In particular, over websocket, server implements a kind of Keep Alive protocol (see image below). Every 30sec server sends a ping to the client and check if previous ping (sent 30 sec ago) has been confirmed with a "pong" ( 😊 ) by the client. If not websocket is disposed. 
Im my opinion, during downloading process client receives late this ping message because sent over same websocket channel used for download (at that time full for downloading). So client is not able to sends pong in time. 

`@theia/core/src/node/messaging/messaging-contribution.ts`
![image](https://user-images.githubusercontent.com/56077774/99537555-206c1500-29ac-11eb-8db1-cd54e54e0327.png)
