### ISSUE TITLE
Not compatible with NodeJS 15.4.0

### ISSUE THREAD

**Issue by ramonck** [theia-ide/theia-apps#451]
Build doesn't work, followed the procedure on this page.
https://theia-ide.org/docs/composing_applications/

Commands:

1. yarn
2. yarn theia build

```
warning @theia/cli > @theia/application-manager > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
error find-git-exec@0.0.3: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <13". Got "15.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

OS

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**Comment by vince-fugnitto** [comment]
@ramonck it is not a version compatible with the framework: 
- https://github.com/eclipse-theia/theia/blob/39887bf9d05c29fedc9466db76ca0a58706a1a2a/package.json#L7

In addition, the `prerequisites` highlight the supported node range:
- https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites

**Comment by vince-fugnitto** [comment]
Closing since the [prerequisites](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites), [composing applications](https://theia-ide.org/docs/composing_applications/) documentation, and error message state the supported `node` range.
