### ISSUE TITLE
CI-CD fails at Docker login 

### ISSUE THREAD

**Issue by DukeNgn** [theia-ide/theia-apps#454]
## Description
To log in and publish images to DockerHub, CI-CD requires `DOCKER_USERNAME` and `DOCKER_PASSWORD` variables to be present in the repo's secrets

Additional links:
+ [The 2 variables in CI-CD file](https://github.com/theia-ide/theia-apps/blob/master/.github/workflows/ci-cd.yml#L119-L120)
+ [CI failing](https://github.com/theia-ide/theia-apps/runs/1688312360#step:8:7)

## Update:
The names of the required 2 variables in the secrets were [updated](https://github.com/theia-ide/theia-apps/blob/master/.github/workflows/ci-cd.yml#L120-L121)
	- `DOCKERHUB_USERNAME`
	- `DOCKERHUB_TOKEN`

cc: @marcdumais-work

**Comment by marcdumais-work** [comment]
cc: @akosyakov : I think we used to have these configured, but I do not see them ATM. Would you add them again?

**Comment by akosyakov** [comment]
@marcdumais-work Marc do you think you can do it or someone from Ericsson team?

**Comment by DukeNgn** [comment]
@akosyakov Unfortunately, I don't think anyone in our team has access to Dockerhub credentials.

**Comment by akosyakov** [comment]
Marc should have an account on dockerhub which is an owner of theia org.

**Comment by marcdumais-work** [comment]
> Marc should have an account on dockerhub which is an owner of theia org.

I'll dig around - maybe I have that account on my personal computer.

**Comment by marcdumais-work** [comment]
@akosyakov confirmed.

**Comment by marcdumais-work** [comment]
I have set the two secrets. I'll relaunch the latest build and see what happens.

**Comment by marcdumais-work** [comment]
Hi @DukeNgn ,

It's not working - `docker login` seems to expect a real password, rather than a security token. I have found this action:
https://github.com/marketplace/actions/docker-login

Can you try using it in place of the current manual docker login? I have setup the secrets to match the names in the example.

**Comment by vince-fugnitto** [comment]
Re-opening as the login was not yet successful.

**Comment by marcdumais-work** [comment]
Let's try this again - I just updated the secrets and will restart a build to test.

**Comment by marcdumais-work** [comment]
Build ongoing: https://github.com/theia-ide/theia-apps/runs/1763190356

**Comment by marcdumais-work** [comment]
I think it worked but there's a delay before the images are visible. I see one now to it's probably fine: 
https://hub.docker.com/r/theiaide/theia-https

![image](https://user-images.githubusercontent.com/25749063/105731789-c59bf000-5efd-11eb-85a3-ff60ed4cbe74.png)
