### ISSUE TITLE
I hope it can match the the  aarch64 platform

### ISSUE THREAD

**Issue by lzwsoldier** [theia-ide/theia-apps#455]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by vince-fugnitto** [comment]
@lzwsoldier thank you for reporting the issue, do you mind providing additional details? (it is not clear what the problem is). I assume you want to use one of the example docker images with an `arm64` architecture?

**Comment by marcdumais-work** [comment]
Might be related to:

https://github.com/docker/for-linux/issues/1170
