### ISSUE TITLE
Activating extension Python Failed 

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [theia-ide/theia-apps#461]
Getting below error in `theia` IDE
```
Activating extension 'Python' failed: Dependent extension 'ms-toolsai.jupyter' is not installed.
```

**Comment by vince-fugnitto** [comment]
@DilLip-Chowdary-Codes thank you for reporting the issue, it is a duplicate of https://github.com/theia-ide/theia-apps/issues/441. Newer versions of `ms-python` use a proprietary `ms-toolsai.jupyter` which cannot be published to `open-vsx` or used by non-vscode products it seems.

- https://github.com/theia-ide/theia-apps/issues/441#issuecomment-772842409
