### ISSUE TITLE
New java docker image

### ISSUE THREAD

**Issue by GavinHuang96** [theia-ide/theia-apps#464]
Is it possible for you to update the docker image for java? I saw the last update was five months ago. Thanks.

**Comment by vince-fugnitto** [comment]
@GavinHuang96 the `theia-java` docker image has been removed from the repository (https://github.com/theia-ide/theia-apps/pull/408). You can either use the `theia-full` image or implement and maintain your own image for java development as these images are for test and reference purposes. There is no plan at the moment to bring back or publish new java images.
