### ISSUE TITLE
theia app based on Qt WebEngine

### ISSUE THREAD

**Issue by simevo** [theia-ide/theia-apps#468]
I wrapped theia as a standalone Desktop app using Qt WebEngine: https://gitlab.com/simevo/theia-app

This avoids the bulky Electron runtime (the executable is a mere 29 kB). Please consider including this version in your collection.

**Comment by vince-fugnitto** [comment]
@simevo thank you for your interest in the project and implementing an alternative to using `electron`. 

From what I understand _Qt WebEngine_ is commercial (paid)?
The [licensing](https://doc.qt.io/qt-5/qtwebengine-licensing.html) also seems problematic for an open-source project, and does not seem to satisfy any of those present in the [eclipse foundation approved license list](https://www.eclipse.org/legal/licenses.php#approved).

**Comment by simevo** [comment]
Qt in general is [dual-licensed](https://www.qt.io/licensing/open-source-lgpl-obligations), the Qt WebEngine add-on in particular is not one of the ["commercial or GPL-only modules"](https://doc.qt.io/qt-5/qtmodules.html#gpl-licensed-addons). This is confirmed by the license for the `qtwebengine-opensource-src` package [in Debian main](https://tracker.debian.org/media/packages/q/qtwebengine-opensource-src/copyright-5.15.2dfsg-3): LGPL-3 or GPL-2.

Not sure whether all this is compatible with your rules.

**Comment by vince-fugnitto** [comment]
In order to use `Qt` for open-source there are some terms that I'm not sure is acceptable for the community:

- https://www.qt.io/download-open-source?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5

> The Qt framework is available under both open source and commercial licenses. This dual-licensing model is based on the principal of quid pro quo – roughly meaning “something for something.”
>
> Simply put, this is how it works:  In return for the value you receive from using Qt to create your application, you are expected to give back by contributing to Qt or buying Qt.

cc @marcdumais-work

**Comment by marcdumais-work** [comment]
@vince-fugnitto I agree - I do not think this license will fly for us. Thanks nonetheless @simevo for the  suggestion.
