### ISSUE TITLE
Deploy on cloud

### ISSUE THREAD

**Issue by Vansh1411** [theia-ide/theia-apps#470]
Can anyone guide how to deploy it on railways.app, heroku, etc. Free cloud platform just like code-server has guided in their repo.

**Comment by vince-fugnitto** [comment]
Thank you for the discussion, there is no deployment guide as far as I know, deploying a theia-based application should not be any different than other web applications.

You might want to look at official [heroku](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml) documentation, or inspire yourself from previous efforts such as the following. I have never tested it out myself however:
- https://github.com/jackvz/theia-ide-on-heroku

**Comment by Vansh1411** [comment]
But I think you should try for the railway.app because it's way better than heroku so if you could help it will be very helpful.

**Comment by vince-fugnitto** [comment]
@Vansh1411 I don’t have any experience with `railway.app` nor do I know of anyone in the community who has deployed a theia-based application on railway. Unfortunately I don’t believe I can be of much help.

Your best bet would be to follow official `railway.app` documentation, and make use of any appropriate starter examples if possible.
