### ISSUE TITLE
theia-https, works from local lan, doesn’t load from outside

### ISSUE THREAD

**Issue by AntouanK** [theia-ide/theia-apps#480]
hi there.

trying the https image with the auth token.
I’m using a command like
```
docker run -d --name theia --expose 15100 -p 15100:15100 -e server=:15100 -v "$(pwd):/home/project:cached" theiaide/theia-https
```

If I go on another machine on the same LAN, and do https://192.168.1.xxx:15100 , the site loads, I put the token and all is good.
I also forward that 15100 port outside.
So if I go to https://mydomain.com:15100 , I get the first screen that asks for the token.
I put the token, it redirects to https://mydomain.com:15100/?token=xxxxxxxxx as it should , but I only see this : 
![DAF0E5F7-FECB-4852-9884-CCCC66D1E5F4](https://user-images.githubusercontent.com/4569111/121306821-96f84200-c8ff-11eb-8149-50f7f5b69081.jpeg)

additionally, if I go to https://mydomain.com:15100/?token=xxxxxxxxx from the machine in my LAN, it also works fine.

I’m on an ipad so I cannot open the dev tools to debug it. Any idea what might be going wrong???
Is there anything that would make it stop to that loading screen?

Thank you

**Comment by AntouanK** [comment]
to update on this, i think it's an ipad issue.
it works fine on a desktop pc outside the lan, but on ipad on all browsers it gets stuck on loading

**Comment by vince-fugnitto** [comment]
> to update on this, i think it's an ipad issue.
> it works fine on a desktop pc outside the lan, but on ipad on all browsers it gets stuck on loading

@AntouanK thank you for providing an update and confirming it is likely an issue with iPad.

**Comment by AntouanK** [comment]
unfortunately I do not have an apple laptop to be able to see the console of the browser and debug it.
all browsers on ipad pro are basically safari webkit, so there's some bug with that I suppose.

for now I found this https://github.com/cdr/code-server , and I'm trying it out.
looks to work fine on ipad so far 🤞
