### ISSUE TITLE
Docker - Installing open-vsix extension through corporate proxy

### ISSUE THREAD

**Issue by lavaude** [theia-ide/theia-apps#481]
Hello,

I am using the docker image theia-full 1.14.0 locally on my computer and I am trying to install some extensions via the open vsx registry. No success so far, if I inspect the logs of my container I can see the following:

```
root INFO [kelvin.vscode-sshfs]: trying to resolve latest version...
root ERROR Failed to resolve plugins from 'vscode:extension/kelvin.vscode-sshfs' Error: connect ECONNREFUSED 198.41.30.195:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
root INFO Deploy plugin entry took: 21226.3 ms
```

Is there any specific way to set the proxy for installing extensions?
If I am going through theia terminal or by directly connecting to my container, I am "theia" user, all proxies are well set (http_proxy, https_proxy etc...) and I can curl/git/wget... 

But when installing an extension it seems to go through the root user (logs upper).

Any ideas?

Cheers,

Edouard

**Comment by marcdumais-work** [comment]
> I am "theia" user, all proxies are well set (http_proxy, https_proxy etc...) and I can curl/git/wget...

How did you set them up? The Theia app is started as the [container's entry point ](https://github.com/theia-ide/theia-apps/blob/master/theia-full-docker/Dockerfile#L325), and so any change you make to the environment, e.g. in a Theia terminal, will unfortunately not be effective inside the app. It's a generic Docker limitation, with its immutability philosophy. 

If you do not mind a bit of manual work, I think it's possible to override the entrypoint to `/bin/bash`, modify the environment from the bash terminal, and from that same terminal, start the Theia app.
