### ISSUE TITLE
Activating extension 'Vetur' failed: The language client requires VS Code version ^1.52.0 but received version 1.44.0

### ISSUE THREAD

**Issue by LiangKangHui** [theia-ide/theia-apps#484]
I found this problem by installing vetur on theia
I am based on the security version built by docker. I want to know how can I change the VS code version. I have seen similar problems on git, but it is theia instead of theia-app
I am a novice, and the English is also from google translation
Hope to get your answers. Thank you very much!

**Comment by LiangKangHui** [comment]
Sorry i installed a lower version

**Comment by marcdumais-work** [comment]
> Sorry i installed a lower version

No problem - thanks for closing the issue once you realised
