### ISSUE TITLE
bug: problematic `@theia/cpp-debug` extension

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia-apps#494]
**Affected Images**:

- **`theia-full-docker`**
- **`theia-cpp-docker`**

**Description**

The `@theia/cpp-debug` extension is causing runtime issues for images since it still targets **es5** while the rest of the `@theia` extensions now target **ES2017**. This causes runtime issues most notably on startup where the top-level menu is missing, and contributions fail to load.

The `@theia/cpp-debug` extension needs to be updated to support **ES2017** and published so apps can make use of newer versions of the framework:
- https://github.com/eclipse-theia/theia-cpp-extensions/pull/123

**Additional Info**

- https://github.com/eclipse-theia/theia/issues/10038
- https://github.com/eclipse-theia/theia/issues/10042

**Comment by marcdumais-work** [comment]
Note: The rust image is also affected - it builds in place @theia/cpp-debug.

**Comment by zedchance** [comment]
Is the fix to this problem to use the `cdt-gdb-vscode` instead of the `@theia/cpp-debug` extension?

**Comment by vince-fugnitto** [comment]
> Is the fix to this problem to use the `cdt-gdb-vscode` instead of the `@theia/cpp-debug` extension?

@zedchance for the time being you could use `cdt-gdb-vscode` until a newer version of `@theia/cpp-debug` is released https://github.com/eclipse-theia/theia-cpp-extensions/issues/130. Else you can use an older version of Theia (prior to the `es2017` upgrade).
