### ISSUE TITLE
Fail to build the image by the dockerfile in repo

### ISSUE THREAD

**Issue by CenGinHong** [theia-ide/theia-apps#501]
I try to build my own image by the dockerfile in repo because published images have been removed from Docker Hub. But it failed because of some errors like 
`executor failed running [/bin/sh -c apk add --no-cache make pkgconfig gcc g++ python libx11-dev libxkbfile-dev libsecret-dev]: exit code: 10`
It is  never happened before.

**Comment by vince-fugnitto** [comment]
@CenGinHong thank you for the issue, I verified and was able to successfully build the [`theia-docker`](https://github.com/theia-ide/theia-apps/tree/master/theia-docker) image (verified without a cache as well):

```bash
$  docker build --no-cache . -t theiaide/theia:latest
```

You might want to try to:
- restart docker
- possibly perform a prune

**Comment by CenGinHong** [comment]
sorry, I tried many times and still failed. I suspected it was a problem with my machine, so I used Alibaba Cloud's Container Registry Service to build and still failed, both `theia-cpp` , `theia-go` and  `theia-python`

**Comment by CenGinHong** [comment]
> @CenGinHong thank you for the issue, I verified and was able to successfully build the [`theia-docker`](https://github.com/theia-ide/theia-apps/tree/master/theia-docker) image (verified without a cache as well):
> 
> ```shell
> $  docker build --no-cache . -t theiaide/theia:latest
> ```
> 
> You might want to try to:
> 
> * restart docker
> * possibly perform a prune

sorry, I tried many times and still failed. I suspected it was a problem with my machine, so I used Alibaba Cloud's Container Registry Service to build and still failed, both `theia-cpp` , `theia-go` and  `theia-python`

**Comment by vince-fugnitto** [comment]
@CenGinHong thank you for the follow-up, it's possible you'll need to update some of the images for them to work.
As part of https://github.com/theia-ide/theia-apps/issues/496 we have decided to slowly ramp down the repository including the publishing and maintenance of images. This means it is possible that some images are not working completely, and may require maintenance updates.
