### ISSUE TITLE
The offical docker images is not exist

### ISSUE THREAD

**Issue by blue7wings** [theia-ide/theia-apps#503]
theia app images is not exist in docker hub, could you build it and upload to docker hub?

**Comment by vince-fugnitto** [comment]
@blue7wings thank you for reporting the issue, please note that images are no longer being published on dockerhub (https://github.com/theia-ide/theia-apps/pull/497), and there are plans to archive the repository in favor of a different solution (https://github.com/theia-ide/theia-apps/issues/496). However, you can still use the examples present in the repository as reference to build and maintain your own images.
