### ISSUE TITLE
Docker images 404 - cannot pull 

### ISSUE THREAD

**Issue by MacGyver27** [theia-ide/theia-apps#509]
Hi,

Docker images not located on Docker Hub. 
![image](https://user-images.githubusercontent.com/6546231/146621874-6d735f56-c0e1-431e-80a9-15d649114fdd.png)

```
docker pull theiaide/theia:latest
Error response from daemon: pull access denied for theiaide/theia, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

docker pull theiaide/theia-full:latest
Error response from daemon: pull access denied for theiaide/theia-full, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Sure I did successful docker login..

Thanks!

**Comment by vince-fugnitto** [comment]
@MacGyver27 thanks for the issue, please see: https://github.com/theia-ide/theia-apps/issues/496

Related:
- https://github.com/theia-ide/theia-apps/issues/508
- https://github.com/theia-ide/theia-apps/issues/503

**Comment by MacGyver27** [comment]
So how do I run it now then? Without creating my own docker image? Thanks

**Comment by vince-fugnitto** [comment]
> So how do I run it now then? Without creating my own docker image? Thanks

@MacGyver27 the images aren’t hosted anymore to run directly. Instead, you can use the image’s sources (in this repo) as a reference to build and maintain your own images to suit your needs and use-case(s). The images we had on dockerhub were never official, they were used as examples and for CI purposes, the idea was always for others to only use them as references to build and maintain their own.

**Comment by MacGyver27** [comment]
@vince-fugnitto appreciate the help.. but the build of the theia-full does not work. Mind having a [look](https://github.com/theia-ide/theia-apps/issues/505#issuecomment-997302371) why? Thanks

**Comment by vince-fugnitto** [comment]
@MacGyver27 I’m currently on vacation so I won’t be able to have a look for a while, if you do not need golang support you can simply remove it from the dockerfile, else I would look to update the golang build to get it to work again.

**Comment by MacGyver27** [comment]
Thanks! And enjoy!

**Comment by phil294** [comment]
Could you please update the readme then? Theia's official website links you to this repository, which links you to running theia with Docker, which eventually doesn't work as stated.

**Comment by CiciDongxue** [comment]
您好，我已收到您的来信，暂时无法回复您的邮件，望见谅。

**Comment by vince-fugnitto** [comment]
> Could you please update the readme then? Theia's official website links you to this repository, which links you to running theia with Docker, which eventually doesn't work as stated.

@phil294 thank you for the suggestion, which link are you referring to in the [website](https://theia-ide.org/), I could not find any.

As for this repository, we have a note already about the repo being deprecated and a pinned issue as well. If you're not looking to maintain your own docker image based on the examples you might be interested in the following: https://quay.io/repository/zowe-explorer/theia?tab=tags (maintained by IBM).
