### ISSUE TITLE
[full image] add php support

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#52]
After this is done: https://github.com/theia-ide/theia-php-extension/issues/6

**Comment by pwFoo** [comment]
php support would be great!

**Comment by marcdumais-work** [comment]
Adding partial PHP support in the following PR. For now it's only when using the "next" version of Theia, since ```@theia/php``` does not yet have a ```latest``` published version. 

https://github.com/theia-ide/theia-apps/pull/81

Feedback about which tools we should minimally add to the image, so that it's usable for PHP development, or at least a demo of such. This base can then be used to bootstrap a standalone PHP image in this repo, that can be made fancier if we want.

**Comment by olberger** [comment]
Not sure what the current status is, but I tried my own proposal, in https://github.com/olberger/theia-apps/tree/php/theia-php-docker

The aim is to be able to use composer and php -S in the terminal.
