### ISSUE TITLE
[php] create new image

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#53]
after this is done: https://github.com/theia-ide/theia-php-extension/issues/6

**Comment by pwFoo** [comment]
A image with php support would be great

**Comment by pwFoo** [comment]
Hi @marcdumais-work,

any update with php image?

**Comment by pwFoo** [comment]
Tried to build my own theia image with php support, but it fails with different error messages during theia build...
I hope anyone could build a working / official php image here?
