### ISSUE TITLE
Frontend App not working in Docker - Circular Dependency problem

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia-apps#55]
This is a mirror of theia-ide/theia#2307.

Currently, I used the full `package.json` from theia-ide/theia-apps for my Theia image, and this happened both at latest and next

![image](https://user-images.githubusercontent.com/14976516/42413045-36788924-824b-11e8-9c9e-02d09840c8a5.png)

Further looking at the backend logs - it seems to be at fault at extension manager, caused by `electron.js`.

**Comment by sr229** [comment]
Stack Trace in Backend 

![image](https://user-images.githubusercontent.com/14976516/42417227-487dde64-82b7-11e8-9427-f21d9da8ba0c.png)

**Comment by marcdumais-work** [comment]
@sr229 which image(s) have you seen this happening-with?

**Comment by sr229** [comment]
@marcumais-work I maintain my own images that is based of theia-apps, source is [here](https://github.com/sr229/theia-openshift).

**Comment by sr229** [comment]
Doing more debug - It seems to happen on `@theia/core`

**Comment by sr229** [comment]
Doing more debug - It was not on `@theia/core` rather but on a application that depends on the Theia Packager

**Comment by marcdumais-work** [comment]
@sr229 do you still this issue?

**Comment by sr229** [comment]
@marcdumais-work Persistent still, probably the extension host is probably failing

**Comment by marcdumais-work** [comment]
@sr229 I built and successfully ran the ```latest``` version of your [theia-openshift](https://github.com/sr229/theia-openshift) image (latest master branch). I then noticed that latest.package.json was actually pulling all ```next``` versions of Theia packages. So I also tried with all switched to ```latest```. The image still ran. 

There might be other issues with your image, but Theia is running. 

Closing this issue. Please re-open if needed, providing steps to reproduce the issue.
