### ISSUE TITLE
[all images] add @theia/textmate-grammars 

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#57]
so that we get coloring for html, xml, ...

**Comment by sr229** [comment]
I could probably do this on a clean fork once #56 is merged.

**Comment by akosyakov** [comment]
Do we really need to wait for #56 to make it happen?

**Comment by sr229** [comment]
@akosyakov I need to do a clean fork to be able to make the PR atm - my fork is really dirty.
