### ISSUE TITLE
theia-full-docker: Error: "Cannot apply @injectable decorator multiple times. (due to yangster)

### ISSUE THREAD

**Issue by colemickens** [theia-ide/theia-apps#59]
Cole Mickens: *@akosyakov (had a problem with my docker invocation), I'm still seeing this: "Error: "Cannot apply @injectable decorator multiple times." but I don't really see any other message, just a stack trace that looks not-so-helpful.* 

marcdumais-work: *Hi, I think it's the yang extension causing the issue with the full image. @colemickens you can temporarily remote that one from next.package.json and rebuild the image.
related to theia-ide/yangster#59*

cc: @marcdumais-work

**Comment by JanKoehnlein** [comment]
I pushed a fixed version of `theiaide/theia-full:next`.

**Comment by JanKoehnlein** [comment]
Sorry, still pushing...

**Comment by JanKoehnlein** [comment]
Push completed.

**Comment by marcdumais-work** [comment]
I tried the full image ```theiaide/theia-full:next``` and it worked fine. Baring other issues, a hand-build ```theia-full:next``` image should work just as well. Thanks @JanKoehnlein

**Comment by JanKoehnlein** [comment]
Could you review https://github.com/theia-ide/theia-apps/pull/61 then? It's not merged yet. The image has been created manually from a locally changed config.

**Comment by marcdumais-work** [comment]
oh, missed that. Will do.
