### ISSUE TITLE
GH API token no longer being used?

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#60]
We had more CI failures lately, and from the logs it sounds like the GH token that was previousky setup is no longer being used? 

https://travis-ci.org/theia-ide/theia-apps/jobs/401582950#L606

**Comment by akosyakov** [comment]
It actually was not ever used because we did not declare ARG in docker images. 🙈

**Comment by akosyakov** [comment]
Now it should be used, see https://github.com/theia-ide/theia-apps/pull/66.
