### ISSUE TITLE
Enable Docker Hub Automated Builds

### ISSUE THREAD

**Issue by lanrat** [theia-ide/theia-apps#71]
Would it also be possible to enable [automated builds](https://docs.docker.com/docker-hub/github/) so that whenever an update is pushed to any of the theia Dockerfiles all of the [containers](https://hub.docker.com/u/theiaide/) are also updated automatically?

Currently some of your containers (like full) lag behind the others, and it is not clear when updates are manually pushed.

Thanks.

**Comment by akosyakov** [comment]
> Would it also be possible to enable automated builds so that whenever an update is pushed to any of the theia Dockerfiles all of the containers are also updated automatically?

Do they work across repositories, meaning that a build should use Dockerfile from one repository (theia-apps) and react on changes from another (thiea-ide)? Last time I looked they could not.

> Currently some of your containers (like full) lag behind the others, and it is not clear when updates are manually pushed.

All images are rebuilt nightly. Which lag do you mean?

**Comment by jgroom33** [comment]
@lanrat are you referring to only `next` being available [here](https://hub.docker.com/r/theiaide/theia-full/tags/) and the theia-ide shows `next` and `latest` (so we should assume that a semantic versioned release should also be available for full?)

**Comment by lanrat** [comment]
> Do they work across repositories, meaning that a build should use Dockerfile from one repository (theia-apps) and react on changes from another (thiea-ide)? Last time I looked they could not.

Good point. You can have another Docker Hub repository build trigger another (ex: when the `node` image is updated re-build an image dependent on `node`), but it likely won't for projects like this where the Dockerfile is in another repository.

> All images are rebuilt nightly. Which lag do you mean?

I'm asking about all tags, but specifically interested in `:next`
 
> Do they work across repositories, meaning that a build should use Dockerfile from one repository (theia-apps) and react on changes from another (thiea-ide)? Last time I looked they could not.

Yes, I'm currently using `theia-full:next` and wanted to ensure that it would be up to date. It currently looks like it has not had an update in a while while some of the other theia containers get more regular updates.

**Comment by marcdumais-work** [comment]
closed with https://github.com/theia-ide/theia-apps/pull/72

**Comment by marcdumais-work** [comment]
confirmed that ```theiaide/theia-full``` image is now published as part of CI: https://hub.docker.com/r/theiaide/theia-full/tags/
