### ISSUE TITLE
add @theia/tslint to images containing @theia/typescript

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia-apps#82]

**Comment by marcdumais-work** [comment]
We could add ```@theia/tslint``` to the various applicable ```next``` images immediately and to the ```latest``` images after this month's release, correct?

**Comment by marcdumais-work** [comment]
I added a commit to this [PR](https://github.com/theia-ide/theia-apps/pull/81) to take care of the ```next``` images part of this issue.
