### ISSUE TITLE
Theia when served under a HTTP endpoint does not accept HTTPS requests

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia-apps#89]
you can reproduce this with the Theia OpenShift image and deploy a TLS enabled route on [OpenShift Online](https://manage.openshift.com).
Steps to reproduce:
- Upload the `theia-openshift` image to the OpenShift Online Registry for your project.
- Create a deployment with the image (you may as well use my image to save you time for Step 1 which is `chinodesuuu/theia:latest`)
- After the pod is detected Ready, create route under the application's service.

Expected: Even if it serves under http://0.0.0.0, it should accept incoming requests regardless if router enforced TLS.

Result: It does not serve on TLS-enabled routes or it takes a long time to serve to the route (if you do the same without the TLS, it serves immediately).

**Comment by uniibu** [comment]
Is this issue specific to openshift only? Because I'm currently using Cloudflare(full-strict ssl,tls enabled) and Nginx as reverse proxy which serves a theia docker container and it works fine. Or probably I'm barking in the wrong tree here. If not related, please ignore :)

**Comment by sr229** [comment]
@uniibu seems to be persistent only to OpenShift.
