### ISSUE TITLE
Include plugins mechanism in theia-full docker image

### ISSUE THREAD

**Issue by apupier** [theia-ide/theia-apps#95]
//cc @benoitf

**Comment by marcdumais-work** [comment]
Hi @apupier 

Other than adding ```@theia/plugin``` , ```@theia/plugin-ext``` and ```@theia/plugin-ext-vscode``` in [latest, next]. ```package.json``` of the image, is there anything else to do? Anything else that should also be included?

e.g.: is there a way to also include some existing plugins, even if just to show-off for demo and such?

**Comment by apupier** [comment]
My goal is to be able to test Camel and XML VS Code plugins and Java supports to check that they work well together.
I would guess that Java support is already available.
For Camel and XML VS Code plugin I'm not sure that there is a way to activate them by default already. (but @benoitf knows better)
I think that we can start with plugin/plugin-ext and plugin-ext-vscode first and see for additional plugins. laters. Unless some other modules are required for my previously mentioned goal.

**Comment by benoitf** [comment]
Fixed by https://github.com/theia-ide/theia-apps/pull/96
