### ISSUE TITLE
Custom projects folder 

### ISSUE THREAD

**Issue by uniibu** [theia-ide/theia-apps#98]
At the moment, the projects folder is set to be static at `/home/project` , is it possible to change this and have it customizable during `docker run`? 

It could be set as an `ENV` with a default value. For example:
```
...
ENV THEIA_PROJECT_DIR /home/project
...
RUN echo -e '#!/bin/bash\n exec yarn theia start $THEIA_DIR --hostname=0.0.0.0 $@' > ./theia.sh
RUN chmod +x ./theia.sh
USER theia
ENTRYPOINT [ "./theia.sh" ]
```
This way a custom project folder could be passed during run as an env, like
`docker run -d -p 3000:3000 -e THEIA_PROJECT_DIR=/myworkspace -v $PWD/workspace:/myworkspace theiaide/theia:next`
and if no `THEIA_PROJECT_DIR` passed it'll default to `/home/project`. This could also be done with `--hostname` allowing it to be customizable with defaults.

**Comment by RVN-BR** [comment]
I currently mount the volumes inside /home/project/*... and it works for multiple volumes... any reason for this except for making it neater?
